# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embodied/unity/AssetBundle.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'embodied/unity/AssetBundle.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n embodied/unity/AssetBundle.proto\x12\x0e\x65mbodied.unity\"\xa7\x01\n\x10\x41ssetBundleCache\x12\x16\n\ttimestamp\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12\x0f\n\x07\x62undles\x18\x02 \x03(\t\x12\x1d\n\x10software_version\x18\x64 \x01(\tH\x01\x88\x01\x01\x12\x18\n\x0bmodule_name\x18\x65 \x01(\tH\x02\x88\x01\x01\x42\x0c\n\n_timestampB\x13\n\x11_software_versionB\x0e\n\x0c_module_name\"\x95\x01\n\x0f\x41ssetBundleScan\x12\x16\n\ttimestamp\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12\x1d\n\x10software_version\x18\x64 \x01(\tH\x01\x88\x01\x01\x12\x18\n\x0bmodule_name\x18\x65 \x01(\tH\x02\x88\x01\x01\x42\x0c\n\n_timestampB\x13\n\x11_software_versionB\x0e\n\x0c_module_name\"\xa9\x01\n\x12\x41ssetBundleRelease\x12\x16\n\ttimestamp\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12\x0f\n\x07\x62undles\x18\x02 \x03(\t\x12\x1d\n\x10software_version\x18\x64 \x01(\tH\x01\x88\x01\x01\x12\x18\n\x0bmodule_name\x18\x65 \x01(\tH\x02\x88\x01\x01\x42\x0c\n\n_timestampB\x13\n\x11_software_versionB\x0e\n\x0c_module_name\"\xa8\x01\n\x11\x41ssetBundleReload\x12\x16\n\ttimestamp\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12\x0f\n\x07\x62undles\x18\x02 \x03(\t\x12\x1d\n\x10software_version\x18\x64 \x01(\tH\x01\x88\x01\x01\x12\x18\n\x0bmodule_name\x18\x65 \x01(\tH\x02\x88\x01\x01\x42\x0c\n\n_timestampB\x13\n\x11_software_versionB\x0e\n\x0c_module_nameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embodied.unity.AssetBundle_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ASSETBUNDLECACHE']._serialized_start=53
  _globals['_ASSETBUNDLECACHE']._serialized_end=220
  _globals['_ASSETBUNDLESCAN']._serialized_start=223
  _globals['_ASSETBUNDLESCAN']._serialized_end=372
  _globals['_ASSETBUNDLERELEASE']._serialized_start=375
  _globals['_ASSETBUNDLERELEASE']._serialized_end=544
  _globals['_ASSETBUNDLERELOAD']._serialized_start=547
  _globals['_ASSETBUNDLERELOAD']._serialized_end=715
# @@protoc_insertion_point(module_scope)
