# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embodied/unity/AudioNotif.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'embodied/unity/AudioNotif.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x65mbodied/unity/AudioNotif.proto\x12\x0e\x65mbodied.unity\"b\n\x16\x41udioNotifPauseEventPB\x12\x15\n\x08\x64uration\x18\x01 \x01(\x02H\x00\x88\x01\x01\x12\x16\n\ttimestamp\x18\x02 \x01(\x04H\x01\x88\x01\x01\x42\x0b\n\t_durationB\x0c\n\n_timestamp\"b\n\x1c\x41udioNotifSpeedChangeEventPB\x12\x12\n\x05speed\x18\x01 \x01(\x02H\x00\x88\x01\x01\x12\x16\n\ttimestamp\x18\x02 \x01(\x04H\x01\x88\x01\x01\x42\x08\n\x06_speedB\x0c\n\n_timestamp\"e\n\x1d\x41udioNotifVolumeChangeEventPB\x12\x13\n\x06volume\x18\x01 \x01(\x02H\x00\x88\x01\x01\x12\x16\n\ttimestamp\x18\x02 \x01(\x04H\x01\x88\x01\x01\x42\t\n\x07_volumeB\x0c\n\n_timestamp\">\n\x16\x41udioIsFinishedEventPB\x12\x16\n\ttimestamp\x18\x01 \x01(\x04H\x00\x88\x01\x01\x42\x0c\n\n_timestamp\"?\n\x17\x41udioNotifResumeEventPB\x12\x16\n\ttimestamp\x18\x01 \x01(\x04H\x00\x88\x01\x01\x42\x0c\n\n_timestamp\"=\n\x15\x41udioNotifChatEventPB\x12\x16\n\tchatEvent\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x0c\n\n_chatEventb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embodied.unity.AudioNotif_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIONOTIFPAUSEEVENTPB']._serialized_start=51
  _globals['_AUDIONOTIFPAUSEEVENTPB']._serialized_end=149
  _globals['_AUDIONOTIFSPEEDCHANGEEVENTPB']._serialized_start=151
  _globals['_AUDIONOTIFSPEEDCHANGEEVENTPB']._serialized_end=249
  _globals['_AUDIONOTIFVOLUMECHANGEEVENTPB']._serialized_start=251
  _globals['_AUDIONOTIFVOLUMECHANGEEVENTPB']._serialized_end=352
  _globals['_AUDIOISFINISHEDEVENTPB']._serialized_start=354
  _globals['_AUDIOISFINISHEDEVENTPB']._serialized_end=416
  _globals['_AUDIONOTIFRESUMEEVENTPB']._serialized_start=418
  _globals['_AUDIONOTIFRESUMEEVENTPB']._serialized_end=481
  _globals['_AUDIONOTIFCHATEVENTPB']._serialized_start=483
  _globals['_AUDIONOTIFCHATEVENTPB']._serialized_end=544
# @@protoc_insertion_point(module_scope)
