# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embodied/unity/enums.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'embodied/unity/enums.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x65mbodied/unity/enums.proto\x12\x0e\x65mbodied.unity*f\n\x11MpuShakeDirection\x12\x06\n\x02Up\x10\x00\x12\x08\n\x04Roll\x10\x01\x12\t\n\x05Pitch\x10\x02\x12\x07\n\x03Yaw\x10\x03\x12\r\n\tLeftRight\x10\x04\x12\x0f\n\x0b\x46orwardBack\x10\x05\x12\x0b\n\x07Invalid\x10\x06\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embodied.unity.enums_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MPUSHAKEDIRECTION']._serialized_start=46
  _globals['_MPUSHAKEDIRECTION']._serialized_end=148
# @@protoc_insertion_point(module_scope)
