# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embodied/unity/Gaze.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'embodied/unity/Gaze.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x65mbodied/unity/Gaze.proto\x12\x0e\x65mbodied.unity\"\xf8\x02\n\x04Gaze\x12\x18\n\x0bidEyeTarget\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12\x17\n\neyeTargetX\x18\x02 \x01(\x02H\x01\x88\x01\x01\x12\x17\n\neyeTargetY\x18\x03 \x01(\x02H\x02\x88\x01\x01\x12\x17\n\neyeTargetZ\x18\x04 \x01(\x02H\x03\x88\x01\x01\x12\x19\n\x0cidHeadTarget\x18\x05 \x01(\x04H\x04\x88\x01\x01\x12\x18\n\x0bheadTargetX\x18\x06 \x01(\x02H\x05\x88\x01\x01\x12\x18\n\x0bheadTargetY\x18\x07 \x01(\x02H\x06\x88\x01\x01\x12\x18\n\x0bheadTargetZ\x18\x08 \x01(\x02H\x07\x88\x01\x01\x12\x16\n\ttimestamp\x18\t \x01(\x04H\x08\x88\x01\x01\x42\x0e\n\x0c_idEyeTargetB\r\n\x0b_eyeTargetXB\r\n\x0b_eyeTargetYB\r\n\x0b_eyeTargetZB\x0f\n\r_idHeadTargetB\x0e\n\x0c_headTargetXB\x0e\n\x0c_headTargetYB\x0e\n\x0c_headTargetZB\x0c\n\n_timestampb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embodied.unity.Gaze_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GAZE']._serialized_start=46
  _globals['_GAZE']._serialized_end=422
# @@protoc_insertion_point(module_scope)
