# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embodied/unity/MarkUpToolMessages.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'embodied/unity/MarkUpToolMessages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'embodied/unity/MarkUpToolMessages.proto\x12\x16\x65mbodied.TTSMarkupTool\"o\n\x11MarkUpEditRequest\x12\x16\n\ttimestamp\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12\x0f\n\x02id\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x12\n\x05input\x18\x03 \x01(\tH\x02\x88\x01\x01\x42\x0c\n\n_timestampB\x05\n\x03_idB\x08\n\x06_input\"\xd2\x01\n\x12MarkUpEditResponse\x12\x16\n\ttimestamp\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12\x0f\n\x02id\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x12\n\x05input\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x13\n\x06output\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\x15\n\x08revision\x18\x05 \x01(\x04H\x04\x88\x01\x01\x12\x12\n\x05\x65nded\x18\x06 \x01(\x08H\x05\x88\x01\x01\x42\x0c\n\n_timestampB\x05\n\x03_idB\x08\n\x06_inputB\t\n\x07_outputB\x0b\n\t_revisionB\x08\n\x06_ended\"?\n\x17MarkUpEditorClosedEvent\x12\x16\n\ttimestamp\x18\x01 \x01(\x04H\x00\x88\x01\x01\x42\x0c\n\n_timestamp\"[\n\x11MarkUpLineRequest\x12\x16\n\ttimestamp\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12\x14\n\x07\x66orward\x18\x02 \x01(\x08H\x01\x88\x01\x01\x42\x0c\n\n_timestampB\n\n\x08_forward\"X\n\x12MarkUpLineResponse\x12\x16\n\ttimestamp\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12\x12\n\x05valid\x18\x02 \x01(\x08H\x01\x88\x01\x01\x42\x0c\n\n_timestampB\x08\n\x06_validb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embodied.unity.MarkUpToolMessages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MARKUPEDITREQUEST']._serialized_start=67
  _globals['_MARKUPEDITREQUEST']._serialized_end=178
  _globals['_MARKUPEDITRESPONSE']._serialized_start=181
  _globals['_MARKUPEDITRESPONSE']._serialized_end=391
  _globals['_MARKUPEDITORCLOSEDEVENT']._serialized_start=393
  _globals['_MARKUPEDITORCLOSEDEVENT']._serialized_end=456
  _globals['_MARKUPLINEREQUEST']._serialized_start=458
  _globals['_MARKUPLINEREQUEST']._serialized_end=549
  _globals['_MARKUPLINERESPONSE']._serialized_start=551
  _globals['_MARKUPLINERESPONSE']._serialized_end=639
# @@protoc_insertion_point(module_scope)
