# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embodied/unity/NetworkState.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'embodied/unity/NetworkState.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!embodied/unity/NetworkState.proto\x12\x0e\x65mbodied.unity\"v\n\x0cNetworkState\x12\x16\n\tConnected\x18\x01 \x01(\x08H\x00\x88\x01\x01\x12\x11\n\x04Ping\x18\x02 \x01(\x05H\x01\x88\x01\x01\x12\x16\n\ttimestamp\x18\x03 \x01(\x04H\x02\x88\x01\x01\x42\x0c\n\n_ConnectedB\x07\n\x05_PingB\x0c\n\n_timestampb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embodied.unity.NetworkState_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NETWORKSTATE']._serialized_start=53
  _globals['_NETWORKSTATE']._serialized_end=171
# @@protoc_insertion_point(module_scope)
