# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embodied/unity/RobotCamera.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'embodied/unity/RobotCamera.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n embodied/unity/RobotCamera.proto\x12\x0e\x65mbodied.unity\"\xcf\x03\n\x0bRobotCamera\x12\x15\n\x08\x63\x65nter_x\x18\x02 \x01(\x02H\x00\x88\x01\x01\x12\x15\n\x08\x63\x65nter_y\x18\x03 \x01(\x02H\x01\x88\x01\x01\x12\x15\n\x08\x63\x65nter_z\x18\x04 \x01(\x02H\x02\x88\x01\x01\x12\x15\n\x08target_x\x18\x05 \x01(\x02H\x03\x88\x01\x01\x12\x15\n\x08target_y\x18\x06 \x01(\x02H\x04\x88\x01\x01\x12\x15\n\x08target_z\x18\x07 \x01(\x02H\x05\x88\x01\x01\x12\x11\n\x04up_x\x18\x08 \x01(\x02H\x06\x88\x01\x01\x12\x11\n\x04up_y\x18\t \x01(\x02H\x07\x88\x01\x01\x12\x11\n\x04up_z\x18\n \x01(\x02H\x08\x88\x01\x01\x12\x10\n\x03\x66ov\x18\x0b \x01(\x02H\t\x88\x01\x01\x12\x13\n\x06\x61spect\x18\x0c \x01(\x02H\n\x88\x01\x01\x12\x11\n\x04near\x18\r \x01(\x02H\x0b\x88\x01\x01\x12\x10\n\x03\x66\x61r\x18\x0e \x01(\x02H\x0c\x88\x01\x01\x12\x16\n\ttimestamp\x18\x0f \x01(\x04H\r\x88\x01\x01\x42\x0b\n\t_center_xB\x0b\n\t_center_yB\x0b\n\t_center_zB\x0b\n\t_target_xB\x0b\n\t_target_yB\x0b\n\t_target_zB\x07\n\x05_up_xB\x07\n\x05_up_yB\x07\n\x05_up_zB\x06\n\x04_fovB\t\n\x07_aspectB\x07\n\x05_nearB\x06\n\x04_farB\x0c\n\n_timestampb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embodied.unity.RobotCamera_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROBOTCAMERA']._serialized_start=53
  _globals['_ROBOTCAMERA']._serialized_end=516
# @@protoc_insertion_point(module_scope)
