# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embodied/unity/RobotPosition.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'embodied/unity/RobotPosition.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"embodied/unity/RobotPosition.proto\x12\x0e\x65mbodied.unity\"\xdf\x03\n\rRobotPosition\x12\x16\n\ttimestamp\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12\x1c\n\x0f\x63\x61mera_center_x\x18\x02 \x01(\x02H\x01\x88\x01\x01\x12\x1c\n\x0f\x63\x61mera_center_y\x18\x03 \x01(\x02H\x02\x88\x01\x01\x12\x1c\n\x0f\x63\x61mera_center_z\x18\x04 \x01(\x02H\x03\x88\x01\x01\x12\x1c\n\x0f\x63\x61mera_target_x\x18\x05 \x01(\x02H\x04\x88\x01\x01\x12\x1c\n\x0f\x63\x61mera_target_y\x18\x06 \x01(\x02H\x05\x88\x01\x01\x12\x1c\n\x0f\x63\x61mera_target_z\x18\x07 \x01(\x02H\x06\x88\x01\x01\x12\x18\n\x0b\x63\x61mera_up_x\x18\x08 \x01(\x02H\x07\x88\x01\x01\x12\x18\n\x0b\x63\x61mera_up_y\x18\t \x01(\x02H\x08\x88\x01\x01\x12\x18\n\x0b\x63\x61mera_up_z\x18\n \x01(\x02H\t\x88\x01\x01\x42\x0c\n\n_timestampB\x12\n\x10_camera_center_xB\x12\n\x10_camera_center_yB\x12\n\x10_camera_center_zB\x12\n\x10_camera_target_xB\x12\n\x10_camera_target_yB\x12\n\x10_camera_target_zB\x0e\n\x0c_camera_up_xB\x0e\n\x0c_camera_up_yB\x0e\n\x0c_camera_up_zb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embodied.unity.RobotPosition_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROBOTPOSITION']._serialized_start=55
  _globals['_ROBOTPOSITION']._serialized_end=534
# @@protoc_insertion_point(module_scope)
