# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embodied/unity/UserData.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'embodied/unity/UserData.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x65mbodied/unity/UserData.proto\x12\x0e\x65mbodied.unity\"\x86\x04\n\x12UserPairingRequest\x12\x16\n\ttimestamp\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12\x17\n\nuser_token\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x17\n\npublic_key\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x14\n\x07request\x18\x04 \x01(\rH\x03\x88\x01\x01\x12\x17\n\nsecret_key\x18\x05 \x01(\x0cH\x04\x88\x01\x01\x12\x17\n\nis_staging\x18\x06 \x01(\x08H\x05\x88\x01\x01\x12\x1d\n\x10software_version\x18\x64 \x01(\tH\x06\x88\x01\x01\x12\x18\n\x0bmodule_name\x18\x65 \x01(\tH\x07\x88\x01\x01\"\xa9\x01\n\x0ePairingRequest\x12\x16\n\x12PAIR_UNPAIR_LEGACY\x10\x00\x12\x08\n\x04PAIR\x10\x01\x12\x0f\n\x0bUNPAIR_USER\x10\x02\x12\x0f\n\x0bUNPAIR_FULL\x10\x03\x12\x13\n\x0fUNPAIR_RFS_ONLY\x10\x04\x12\x10\n\x0cRECOVER_USER\x10\x05\x12\x16\n\x12RECOVER_USER_LOCAL\x10\x06\x12\x14\n\x10USER_DATA_UPDATE\x10\x07\x42\x0c\n\n_timestampB\r\n\x0b_user_tokenB\r\n\x0b_public_keyB\n\n\x08_requestB\r\n\x0b_secret_keyB\r\n\x0b_is_stagingB\x13\n\x11_software_versionB\x0e\n\x0c_module_name\"\xb0\x01\n\x0eUserDataStatus\x12\x16\n\ttimestamp\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12\x11\n\x04\x63ode\x18\x02 \x01(\rH\x01\x88\x01\x01\x12\x1d\n\x10software_version\x18\x64 \x01(\tH\x02\x88\x01\x01\x12\x18\n\x0bmodule_name\x18\x65 \x01(\tH\x03\x88\x01\x01\x42\x0c\n\n_timestampB\x07\n\x05_codeB\x13\n\x11_software_versionB\x0e\n\x0c_module_nameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embodied.unity.UserData_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERPAIRINGREQUEST']._serialized_start=50
  _globals['_USERPAIRINGREQUEST']._serialized_end=568
  _globals['_USERPAIRINGREQUEST_PAIRINGREQUEST']._serialized_start=276
  _globals['_USERPAIRINGREQUEST_PAIRINGREQUEST']._serialized_end=445
  _globals['_USERDATASTATUS']._serialized_start=571
  _globals['_USERDATASTATUS']._serialized_end=747
# @@protoc_insertion_point(module_scope)
