# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embodied/launcher/ComponentState.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'embodied/launcher/ComponentState.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&embodied/launcher/ComponentState.proto\x12\x11\x65mbodied.launcher\"\xe8\x01\n\x0e\x43omponentState\x12\x16\n\ttimestamp\x18\x01 \x01(\x01H\x00\x88\x01\x01\x12\x11\n\x04name\x18\x02 \x01(\tH\x01\x88\x01\x01\x12,\n\x05state\x18\x03 \x01(\x0e\x32\x18.embodied.launcher.StateH\x02\x88\x01\x01\x12\x1d\n\x10software_version\x18\x64 \x01(\tH\x03\x88\x01\x01\x12\x18\n\x0bmodule_name\x18\x65 \x01(\tH\x04\x88\x01\x01\x42\x0c\n\n_timestampB\x07\n\x05_nameB\x08\n\x06_stateB\x13\n\x11_software_versionB\x0e\n\x0c_module_name\"\xeb\x01\n\x11SetComponentState\x12\x16\n\ttimestamp\x18\x01 \x01(\x01H\x00\x88\x01\x01\x12\x11\n\x04name\x18\x02 \x01(\tH\x01\x88\x01\x01\x12,\n\x05state\x18\x03 \x01(\x0e\x32\x18.embodied.launcher.StateH\x02\x88\x01\x01\x12\x1d\n\x10software_version\x18\x64 \x01(\tH\x03\x88\x01\x01\x12\x18\n\x0bmodule_name\x18\x65 \x01(\tH\x04\x88\x01\x01\x42\x0c\n\n_timestampB\x07\n\x05_nameB\x08\n\x06_stateB\x13\n\x11_software_versionB\x0e\n\x0c_module_name*<\n\x05State\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07Running\x10\x01\x12\x0e\n\nNotRunning\x10\x02\x12\t\n\x05\x46\x61ult\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embodied.launcher.ComponentState_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATE']._serialized_start=534
  _globals['_STATE']._serialized_end=594
  _globals['_COMPONENTSTATE']._serialized_start=62
  _globals['_COMPONENTSTATE']._serialized_end=294
  _globals['_SETCOMPONENTSTATE']._serialized_start=297
  _globals['_SETCOMPONENTSTATE']._serialized_end=532
# @@protoc_insertion_point(module_scope)
