#!/usr/bin/env python3
"""
Overnight QR-command discovery runner.

- Keeps qr_rig.py alive (headless; relaunches if it dies, clearing the mic first).
- Every few minutes snapshots the rig's per-command statistics.
- Regenerates a findings doc (docs/debugging/qr-command-findings.md): what has been
  tried, and which commands trigger a reaction *consistently* (statistically).
- Commits the findings to git periodically, so there's a growing history.
- Runs until --until HH:MM (default 07:00), then a final snapshot + commit.

Chrome (the fullscreen display Moxie scans) is launched once and left alone; its page
polls the rig so it survives rig relaunches. Run this detached:
  DISPLAY=:1 nohup setsid python3 overnight.py > overnight.log 2>&1 < /dev/null &
"""
import subprocess, time, json, urllib.request, os, sys, argparse, datetime

RIG_DIR=os.path.dirname(os.path.abspath(__file__))
REPO=os.path.abspath(os.path.join(RIG_DIR,"..",".."))
FINDINGS=os.path.join(REPO,"docs","debugging","qr-command-findings.md")
BASE="http://127.0.0.1:8091"

def _get(path):
    try:
        with urllib.request.urlopen(BASE+path,timeout=4) as r: return json.load(r)
    except Exception: return None
def rig_up(): return _get("/current") is not None

def clear_mic():
    subprocess.run(["pkill","-9","arecord"],stderr=subprocess.DEVNULL,stdout=subprocess.DEVNULL)
    time.sleep(2)

def launch_rig():
    clear_mic()
    env={**os.environ,"DISPLAY":os.environ.get("DISPLAY",":1"),"MOXIE_BROKER_HOST":"10.42.0.1"}
    subprocess.Popen(["python3","qr_rig.py","--no-chrome","--autofuzz","--moxie-ip","10.42.0.79"],
        cwd=RIG_DIR,env=env,stdin=subprocess.DEVNULL,
        stdout=open(os.path.join(RIG_DIR,"rig.log"),"a"),stderr=subprocess.STDOUT,start_new_session=True)
    for _ in range(15):
        time.sleep(1)
        if rig_up(): break

def launch_chrome():
    env={**os.environ,"DISPLAY":os.environ.get("DISPLAY",":1")}
    subprocess.run(["pkill","-9","-f","qrrig-chrome"],stderr=subprocess.DEVNULL,stdout=subprocess.DEVNULL)
    subprocess.run(["rm","-rf","/tmp/qrrig-chrome"])
    time.sleep(1)
    subprocess.Popen(["google-chrome","--kiosk","--start-fullscreen",f"{BASE}/display",
        "--user-data-dir=/tmp/qrrig-chrome","--no-first-run","--no-default-browser-check",
        "--disable-session-crashed-bubble"],env=env,stdin=subprocess.DEVNULL,
        stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL,start_new_session=True)

def now(): return datetime.datetime.now().strftime("%Y-%m-%d %H:%M")

def write_findings():
    cur=_get("/current") or {}
    stats=cur.get("stats",{})
    rows=[]
    for lab,st in stats.items():
        sh=st.get("shows",0); rc=st.get("react",0)
        gaps=st.get("gaps",[]); mg=sum(gaps)/len(gaps) if gaps else 0
        rows.append({"label":lab,"shows":sh,"react":rc,
                     "rate":round(rc/sh,2) if sh else 0,"mean_gap":round(mg,2),
                     "max_gap":round(max(gaps),2) if gaps else 0,"payload":st.get("payload","")})
    scanned=len(rows)
    consistent=sorted([r for r in rows if r["shows"]>=3 and r["rate"]>=0.5],
                      key=lambda r:(-r["rate"],-r["mean_gap"]))
    watch=sorted([r for r in rows if r["shows"]>=3 and 0.2<=r["rate"]<0.5],
                 key=lambda r:(-r["rate"],-r["mean_gap"]))[:25]
    allr=sorted(rows,key=lambda r:(-r["rate"],-r["mean_gap"]))
    def tbl(rs):
        out="| command | JSON shape | shows | reacts | rate | mean gap | max gap |\n|---|---|--:|--:|--:|--:|--:|\n"
        for r in rs:
            shape,cmd=(r["label"].split(":",1)+[""])[:2]
            out+=f"| `{cmd}` | {shape} | {r['shows']} | {r['react']} | {r['rate']} | {r['mean_gap']}s | {r['max_gap']}s |\n"
        return out
    md=f"""# QR command discovery — findings log

*Auto-generated by `tools/qr-rig/overnight.py`. Last updated: **{now()}**. Grows over time; the git
history of this file is the record of what's been tried.*

Hunting for **undocumented / factory QR commands** a Moxie's Wifi App acts on. Each candidate is a
QR the robot scans; we listen to its scan beep over a mic and measure the **scan→resume gap**. Normal
re-scan cadence is ~2s; a consistently **longer gap = the robot did something** with that command.
"One long gap" is noise — only commands that react across **many** randomized repeats count.

- **Commands scanned at least 3×:** {sum(1 for r in rows if r['shows']>=3)}  ·  distinct scanned: {scanned}
- **Reaction threshold:** gap ≥ 4.5s  ·  **consistent =** ≥3 scans and ≥50% reaction rate

> ⚠️ Context: this robot is **pre-801** (Google-IoT firmware); QR *relocation* is confirmed
> impossible (see [`live-hardware-debug.md`](live-hardware-debug.md)). This log is pure discovery of
> whatever hidden commands the firmware still responds to.

## 🎯 Consistent reactors (the interesting ones)
{tbl(consistent) if consistent else "_none yet — still gathering data_"}

## 👀 Worth watching (partial/intermittent, 20–50% rate)
{tbl(watch) if watch else "_none yet_"}

## 📋 Everything tried (ranked by reaction rate)
{tbl(allr[:120]) if allr else "_no scans recorded yet_"}
"""
    os.makedirs(os.path.dirname(FINDINGS),exist_ok=True)
    open(FINDINGS,"w").write(md)
    return scanned, len(consistent)

def commit(msg):
    # race-safe: only stage the findings file, rebase-autostash before push so it
    # coexists with other commits happening in the repo during the night.
    for args in (["add",FINDINGS],["commit","-m",msg],
                 ["pull","--rebase","--autostash","origin","main"],["push","origin","main"]):
        subprocess.run(["git","-C",REPO]+args,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)

def main():
    ap=argparse.ArgumentParser(); ap.add_argument("--until",default="07:00")
    ap.add_argument("--snap",type=int,default=300); ap.add_argument("--commit-every",type=int,default=3600)
    ap.add_argument("--no-manage",action="store_true",help="don't launch/keepalive chrome+rig; just snapshot+commit")
    a=ap.parse_args()
    hh,mm=map(int,a.until.split(":"))
    end=datetime.datetime.now().replace(hour=hh,minute=mm,second=0,microsecond=0)
    if end<=datetime.datetime.now(): end+=datetime.timedelta(days=1)
    print(f"overnight runner: until {end} snap={a.snap}s commit={a.commit_every}s no_manage={a.no_manage}",flush=True)
    if not a.no_manage: launch_chrome()
    last_commit=0
    while datetime.datetime.now()<end:
        if not rig_up():
            if a.no_manage: print(f"{now()} rig down (externally managed)",flush=True)
            else: print(f"{now()} rig down -> relaunch",flush=True); launch_rig()
        try:
            scanned,cons=write_findings()
            print(f"{now()} scanned={scanned} consistent={cons}",flush=True)
        except Exception as e:
            print(f"{now()} findings error: {e}",flush=True)
        if time.time()-last_commit>a.commit_every:
            commit(f"qr-findings: snapshot {now()}"); last_commit=time.time()
            print(f"{now()} committed",flush=True)
        time.sleep(a.snap)
    write_findings(); commit(f"qr-findings: final {now()}")
    print(f"{now()} done",flush=True)

if __name__=="__main__": main()
