"""Render a mosquitto ACL from the pairing gate's permit list — pure, stdlib only.

**Generated now, inert until P1.** This is §2.3 of
`docs/architecture/backlog/security-broker-auth.md`. In P0 *no robot authenticates*: the
broker's robot listener carries no `password_file` (a real Moxie presents an RS256 JWT as
its MQTT password — `cloud-protocol.md` E3/E4 — so a password file there would refuse the
robot the appliance exists for). A mosquitto `user <name>` block only ever matches a
username the broker has **verified**, so every `user d_<uuid>` block this module emits
matches nothing today. It is documentation that compiles.

Writing it now is the point: when P1 gives the broker a way to verify a device
(`/broker/auth` behind an auth plugin, or TLS client certs if assumption A1 lands), this
file becomes the enforcement point with no redesign, and `fleet/permits.json` stays the
one place that says which robots are ours.

The output is the **strict** floor — the four `%c` patterns and the supervisor block, and
nothing else. The shipped `mqtt/broker/acl` additionally grants the browser SIM a
read-only fleet view over websockets (see that file); `mqtt/broker/acl-robot` is exactly
this floor. Both are asserted against `render_acl({})` in `sim/tests/test_broker_acl.py`.

Input is the permit record documented in
`docs/architecture/config-and-telemetry-contract.md` — *The pairing gate*:

    {"allow_unverified_bots": false,
     "devices": {"d_<uuid>": {"permitted_at": 1788353318, "label": "Sam's Moxie"}}}

CLI (a P1 slice wires this to `set_permit()`; nothing calls it in P0):

    python3 -m moxie_sdk.broker_acl $MOXIE_DATA_DIR/fleet/permits.json > /path/to/acl
"""
from __future__ import annotations

import json
import re

#: The device subtree, in the four directions the recovered topic map needs
#: (`mqtt-and-conversation.md` §3). `%c` substitutes the CLIENT ID, which every client
#: has whether or not it authenticated — that is what makes a per-device confinement
#: available before device auth is.
PATTERN_FLOOR = (
    "pattern write /devices/%c/events/#",
    "pattern write /devices/%c/state",
    "pattern read  /devices/%c/config",
    "pattern read  /devices/%c/commands/#",
)

#: A device id we are willing to write into a config file mosquitto parses line by line.
#: Deliberately narrower than "anything the console stored": the permit record is written
#: by an HTTP handler, and a label or an id carrying a newline must not be able to forge
#: an extra ACL line (`test_no_injection`). Real ids are `d_<uuid>` (E5).
SAFE_ID = re.compile(r"\A[A-Za-z0-9_.:@+-]{1,128}\Z")

_HEADER = """\
# GENERATED by mqtt/moxie_sdk/broker_acl.py from the pairing gate's permit list.
# Do not edit by hand — every permit change re-renders it.
#
# P0 NOTE: this file is INERT. No robot authenticates yet, so no `user d_<uuid>` block
# below can match. It is the P1 enforcement point, written early on purpose.
# See docs/architecture/backlog/security-broker-auth.md §2.3."""


def render_acl(permits: dict, *, supervisor_user: str = "supervisor") -> str:
    """The permit list as a mosquitto ACL. Pure, deterministic, newline-terminated.

    `permits` is the `fleet/permits.json` record (a missing or malformed one renders the
    floor alone — an ACL that grants nothing is the safe failure). Device blocks are
    emitted in sorted id order so the output is byte-stable for a fixed input, which is
    what lets a writer skip the write when nothing changed.
    """
    permits = permits if isinstance(permits, dict) else {}
    devices = permits.get("devices")
    devices = devices if isinstance(devices, dict) else {}
    open_appliance = bool(permits.get("allow_unverified_bots"))

    ids, rejected = [], 0
    for device_id in devices:
        if isinstance(device_id, str) and SAFE_ID.match(device_id):
            ids.append(device_id)
        else:
            rejected += 1

    out = [_HEADER]
    if open_appliance:
        out += ["#",
                "# allow_unverified_bots is ON: this appliance serves any robot that",
                "# connects, so the blocks below are a record of who is known, not a gate."]
    if rejected:
        out += ["#",
                f"# {rejected} device id(s) omitted: not a usable MQTT identity."]
    out += ["", "# Every client, authenticated or not, gets its own device subtree and",
            "# nothing else. There is deliberately no bare `topic` line before the first",
            "# `user` block.", ""]
    out += list(PATTERN_FLOOR)
    out += ["",
            "# The supervisor is the one fleet-wide identity, and it must authenticate to",
            "# get here. $SYS is supervisor-only: $SYS/broker/log is where every",
            "# d_<uuid> on this appliance is announced.",
            f"user {supervisor_user}",
            "topic readwrite /devices/#",
            "topic read      $SYS/#"]
    for device_id in sorted(ids):
        out += ["", f"user {device_id}", f"topic readwrite /devices/{device_id}/#"]
    return "\n".join(out) + "\n"


def load_permits(path: str) -> dict:
    """Read a permit file. A missing or unreadable one is an empty permit list."""
    try:
        with open(path) as fh:
            data = json.load(fh)
    except (OSError, ValueError):
        return {}
    return data if isinstance(data, dict) else {}


def main(argv=None) -> int:
    import argparse
    ap = argparse.ArgumentParser(
        prog="python3 -m moxie_sdk.broker_acl",
        description="Render a mosquitto ACL from $MOXIE_DATA_DIR/fleet/permits.json "
                    "(inert until broker auth P1 — see security-broker-auth.md §2.3).")
    ap.add_argument("permits", help="path to fleet/permits.json")
    ap.add_argument("-o", "--out", help="write here instead of stdout")
    ap.add_argument("--supervisor-user", default="supervisor")
    args = ap.parse_args(argv)
    text = render_acl(load_permits(args.permits), supervisor_user=args.supervisor_user)
    if args.out:
        with open(args.out, "w") as fh:
            fh.write(text)
    else:
        import sys
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":                                  # pragma: no cover
    raise SystemExit(main())
