# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embodied/system/TimeEvents.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'embodied/system/TimeEvents.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n embodied/system/TimeEvents.proto\x12\x0c\x65mbodied.sys\"\xf2\x01\n\x0cTimeZoneInfo\x12\x16\n\ttimestamp\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12!\n\x14midnight_in_timezone\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x15\n\x08olson_id\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x1d\n\x10software_version\x18\x64 \x01(\tH\x03\x88\x01\x01\x12\x18\n\x0bmodule_name\x18\x65 \x01(\tH\x04\x88\x01\x01\x42\x0c\n\n_timestampB\x17\n\x15_midnight_in_timezoneB\x0b\n\t_olson_idB\x13\n\x11_software_versionB\x0e\n\x0c_module_name\"\xee\x02\n\x10UserAlarmRequest\x12\x16\n\ttimestamp\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12\x15\n\x08timer_id\x18\x02 \x01(\rH\x01\x88\x01\x01\x12\x1a\n\ralarm_expires\x18\x03 \x01(\x04H\x02\x88\x01\x01\x12\x1a\n\ralarm_repeats\x18\x04 \x01(\x04H\x03\x88\x01\x01\x12\x1d\n\x10software_version\x18\x64 \x01(\tH\x04\x88\x01\x01\x12\x18\n\x0bmodule_name\x18\x65 \x01(\tH\x05\x88\x01\x01\"V\n\x0eReservedTimers\x12\x16\n\x12TIMER_ID_USER_WAKE\x10\x00\x12\x17\n\x13TIMER_ID_PARENT_APP\x10\x01\x12\x13\n\x0fTIMER_ID_CUSTOM\x10\x64\x42\x0c\n\n_timestampB\x0b\n\t_timer_idB\x10\n\x0e_alarm_expiresB\x10\n\x0e_alarm_repeatsB\x13\n\x11_software_versionB\x0e\n\x0c_module_name\"\xbc\x01\n\x12UserAlarmTriggered\x12\x16\n\ttimestamp\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12\x15\n\x08timer_id\x18\x02 \x01(\rH\x01\x88\x01\x01\x12\x1d\n\x10software_version\x18\x64 \x01(\tH\x02\x88\x01\x01\x12\x18\n\x0bmodule_name\x18\x65 \x01(\tH\x03\x88\x01\x01\x42\x0c\n\n_timestampB\x0b\n\t_timer_idB\x13\n\x11_software_versionB\x0e\n\x0c_module_nameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embodied.system.TimeEvents_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TIMEZONEINFO']._serialized_start=51
  _globals['_TIMEZONEINFO']._serialized_end=293
  _globals['_USERALARMREQUEST']._serialized_start=296
  _globals['_USERALARMREQUEST']._serialized_end=662
  _globals['_USERALARMREQUEST_RESERVEDTIMERS']._serialized_start=476
  _globals['_USERALARMREQUEST_RESERVEDTIMERS']._serialized_end=562
  _globals['_USERALARMTRIGGERED']._serialized_start=665
  _globals['_USERALARMTRIGGERED']._serialized_end=853
# @@protoc_insertion_point(module_scope)
