"""No tracked Markdown may embed an image from another origin.

THIS GUARD IS WORTH MORE THAN THE IMAGE IT WAS WRITTEN FOR. `README.md` embedded its hero
shot from `github.com/user-attachments/...` for months. Every load of the live docs explorer
threw a `securitypolicyviolation` — `img-src 'self' data: blob:` refused it, correctly — and
nothing in the repo noticed, because the only thing that could see it was a browser pointed
at production. It was found by a hand measurement on 2026-09-04, not by a test. (The full
account: `docs/architecture/backlog/vendor-the-readme-hero.md`.)

An off-site image is three defects at once:
  · the shipped CSP refuses it, so it is a broken image on the live site;
  · it makes the public internet a dependency of a page — and of any browser suite that
    renders that page (see the interception preamble in `sim/test_docs_explorer.mjs`);
  · it breaks the standing repo-self-sufficiency rule. A GitHub user-attachment URL is not
    even a stable address: it belongs to an upload, not to the repo.

So the rule is checked twice over, and the second half is the one with teeth:

  1. NO off-site image reference, in any tracked Markdown.
  2. Every image a doc references RESOLVES to a file that exists, and lives under
     `sim/web/` — the Pages output directory (`wrangler.toml`), i.e. the site root. That is
     not a stylistic preference: `sim/web/docs.js` renders a doc from `docs-bundle/` at a
     different depth than the repo, so it resolves each `<img src>` against the doc's own
     repo path and maps the `sim/web/` prefix onto the site root. An image anywhere else has
     no served URL to map onto and 404s in the explorer while looking fine on GitHub.

Fenced and inline code are NOT references — they are quotations. The backlog doc above
quotes the exact bad URL in a ```html fence, and must stay green. That exemption is itself
tested below, in both directions.

Run:  MOXIE_LLM_API_KEY= .venv/bin/python -m pytest sim/tests/test_no_offsite_images.py -q
"""
import os
import re
import subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))

# The generated byte-for-byte copy of the docs tree. Its *content* is checked (a stale
# bundle carrying a resurrected off-site URL is a real defect), but its relative paths are
# correct at the ORIGINAL's depth, not at the copy's — so rule 2 is checked on the sources.
BUNDLE = "sim/web/docs-bundle/"

# Where a doc image must live: the Pages output directory, which is the site root.
SITE_ROOT = "sim/web/"

_MD_IMAGE = re.compile(r"!\[[^\]]*\]\(\s*<?([^)\s>]+)")          # ![alt](url "title")
_HTML_IMAGE = re.compile(r"<img\b[^>]*?\bsrc\s*=\s*[\"']([^\"']+)[\"']", re.I | re.S)
_OFFSITE = re.compile(r"^(?:[a-z][a-z0-9+.-]*:)?//", re.I)        # https://… , //… , ftp://…
_INLINE_DATA = re.compile(r"^data:", re.I)


def strip_code(text):
    """Blank out fenced blocks and inline code spans, keeping line numbering intact.

    A quotation is not a reference. Lines are replaced by empty ones rather than removed so
    a violation still reports the line number a human can jump to.
    """
    out, in_fence, fence = [], False, ""
    for line in text.splitlines():
        m = re.match(r"^\s*(`{3,}|~{3,})", line)
        if m and (not in_fence or line.strip().startswith(fence)):
            in_fence, fence = (not in_fence), (m.group(1) if not in_fence else "")
            out.append("")
            continue
        out.append("" if in_fence else re.sub(r"`[^`]*`", "", line))
    return out


def image_refs(text):
    """[(line_number, url)] for every image the RENDERED document would request."""
    refs = []
    for n, line in enumerate(strip_code(text), 1):
        for rx in (_MD_IMAGE, _HTML_IMAGE):
            for m in rx.finditer(line):
                refs.append((n, m.group(1).strip()))
    return refs


def tracked_markdown():
    """Every tracked .md path, repo-relative, with a filesystem fallback off a checkout."""
    try:
        out = subprocess.run(["git", "ls-files", "-z", "--", "*.md"],
                             cwd=REPO, capture_output=True, text=True, check=True).stdout
        paths = [p for p in out.split("\0") if p]
        if paths:
            return sorted(paths)
    except (OSError, subprocess.CalledProcessError):
        pass
    paths = []
    skip = {".git", "node_modules", ".venv", "__pycache__", "dist"}
    for dirpath, dirs, names in os.walk(REPO):
        dirs[:] = [d for d in dirs if d not in skip]
        for n in names:
            if n.endswith(".md"):
                paths.append(os.path.relpath(os.path.join(dirpath, n), REPO).replace(os.sep, "/"))
    return sorted(paths)


def read(rel):
    with open(os.path.join(REPO, rel), encoding="utf-8", errors="replace") as fh:
        return fh.read()


def test_the_repo_actually_has_markdown_to_scan():
    """A scanner over an empty list passes every assertion below vacuously."""
    docs = tracked_markdown()
    assert len(docs) > 100, "expected the whole doc tree, got %d files" % len(docs)
    assert "README.md" in docs


def test_no_tracked_markdown_embeds_an_offsite_image():
    """Rule 1 — the violation this file was written for, stated as a test."""
    bad = []
    for rel in tracked_markdown():
        for n, url in image_refs(read(rel)):
            if _OFFSITE.match(url):
                bad.append("%s:%d  %s" % (rel, n, url))
    assert not bad, (
        "off-site image(s) in tracked Markdown — the shipped `img-src 'self' data: blob:` "
        "REFUSES these, so they are broken images on the live site, and they make the "
        "public internet a dependency of every suite that renders the page.\n  " +
        "\n  ".join(bad) +
        "\nFix: commit the image under sim/web/img/ and reference it repo-relative "
        "(see sim/web/img/README.md).")


def test_every_doc_image_resolves_to_a_file_under_the_site_root():
    """Rule 2 — the half that keeps GitHub and the docs explorer showing the same picture."""
    bad = []
    for rel in tracked_markdown():
        if rel.startswith(BUNDLE):
            continue                              # generated copy; checked at its source
        base = os.path.dirname(rel)
        for n, url in image_refs(read(rel)):
            if _OFFSITE.match(url) or _INLINE_DATA.match(url):
                continue                          # rule 1 owns off-site; data: is inline
            target = os.path.normpath(os.path.join(base, url.split("#")[0].split("?")[0]))
            target = target.replace(os.sep, "/")
            if not os.path.isfile(os.path.join(REPO, target)):
                bad.append("%s:%d  %s -> MISSING %s" % (rel, n, url, target))
            elif not target.startswith(SITE_ROOT):
                bad.append("%s:%d  %s -> %s is outside %s, so the docs explorer has no URL "
                           "for it" % (rel, n, url, target, SITE_ROOT))
    assert not bad, "\n  ".join([""] + bad)


def test_the_readme_hero_is_vendored_and_is_a_real_image():
    """The specific fix, pinned: a repo-relative src pointing at real image bytes.

    Named rather than left to the sweep above so the regression has a test with its own
    name, and so `width=` staying truthful is checked against the file's actual header.
    """
    refs = image_refs(read("README.md"))
    assert refs, "README.md lost its hero image entirely"
    n, url = refs[0]
    assert url == "sim/web/img/sim-hero.png", "README hero src is %r" % url
    blob = open(os.path.join(REPO, url), "rb").read()
    assert blob[:8] == b"\x89PNG\r\n\x1a\n", "not a PNG: %r" % blob[:8]
    width = int.from_bytes(blob[16:20], "big")
    assert width >= 712, "hero is %dpx wide; README renders it at width=712" % width


# --------------------------------------------------------------------------------------
# Negative controls. Without these the three tests above are equally consistent with
# "the repo is clean" and "the scanner matches nothing at all".
# --------------------------------------------------------------------------------------

_BAD = 'https://github.com/user-attachments/assets/00000000-0000-0000-0000-000000000000'


def test_the_scanner_catches_a_planted_offsite_image(tmp_path):
    doc = tmp_path / "planted.md"
    doc.write_text(
        "# A doc\n\ntext\n\n"
        '<p align="center"><img width="712" alt="x" src="%s" /></p>\n\n'
        "more text\n\n"
        "![a markdown one](http://example.invalid/pic.jpg)\n" % _BAD,
        encoding="utf-8")
    found = [u for _n, u in image_refs(doc.read_text(encoding="utf-8")) if _OFFSITE.match(u)]
    assert len(found) == 2, "the scanner missed a planted off-site image: %r" % (found,)
    assert found[0].startswith("https://github.com/user-attachments/")
    assert found[1] == "http://example.invalid/pic.jpg"


def test_the_scanner_catches_a_planted_broken_local_image(tmp_path):
    """Rule 2's control: a repo-relative src that points at nothing must not slip through."""
    doc = tmp_path / "planted2.md"
    doc.write_text('<img src="img/does-not-exist.png">\n', encoding="utf-8")
    refs = image_refs(doc.read_text(encoding="utf-8"))
    assert [u for _n, u in refs] == ["img/does-not-exist.png"]
    assert not os.path.isfile(os.path.join(REPO, "img/does-not-exist.png"))


def test_quoted_urls_in_code_are_not_references(tmp_path):
    """The other direction: the exemption must not be a hole big enough to hide a real one.

    A doc that DISCUSSES the bad URL — as the backlog entry does — stays green; the same URL
    one line outside the fence does not.
    """
    doc = tmp_path / "quoting.md"
    doc.write_text(
        "# Filed finding\n\n"
        "```html\n"
        '<img width="712" alt="Moxie SIL simulator" src="%s" />\n'
        "```\n\n"
        'and inline: `<img src="%s">` is also only a quotation.\n' % (_BAD, _BAD),
        encoding="utf-8")
    assert image_refs(doc.read_text(encoding="utf-8")) == []
    doc.write_text(doc.read_text(encoding="utf-8") + '\n<img src="%s">\n' % _BAD, encoding="utf-8")
    assert len(image_refs(doc.read_text(encoding="utf-8"))) == 1


def test_the_backlog_entry_that_quotes_the_bad_url_is_green():
    """The real file, not a fixture: it quotes the exact URL and must pass rule 1."""
    rel = "docs/architecture/backlog/vendor-the-readme-hero.md"
    raw = read(rel)
    assert "user-attachments" in raw, "%s no longer quotes the URL; this control is stale" % rel
    assert [u for _n, u in image_refs(raw) if _OFFSITE.match(u)] == []
