"""No tracked Markdown may embed an off-site image, and every doc image must resolve under
`sim/web/` (the Pages site root the docs explorer serves).

An off-site image is refused by the shipped CSP (`img-src 'self' data: blob:`), makes the
internet a dependency of the rendered page, and breaks repo self-sufficiency — the README
hero did exactly this, visible only to a browser pointed at production. Code spans and
fences are quotations, not references.
"""
import os
import re
import subprocess

import pytest

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))

# The generated byte-for-byte copy of the docs tree. Its *content* is checked (a stale
# bundle carrying a resurrected off-site URL is a real defect), but its relative paths are
# correct at the ORIGINAL's depth, not at the copy's — so rule 2 is checked on the sources.
BUNDLE = "sim/web/docs-bundle/"

# Where a doc image must live: the Pages output directory, which is the site root.
SITE_ROOT = "sim/web/"

_MD_IMAGE = re.compile(r"!\[[^\]]*\]\(\s*<?([^)\s>]+)")          # ![alt](url "title")
_HTML_IMAGE = re.compile(r"<img\b[^>]*?\bsrc\s*=\s*[\"']([^\"']+)[\"']", re.I | re.S)
_OFFSITE = re.compile(r"^(?:[a-z][a-z0-9+.-]*:)?//", re.I)        # https://… , //… , ftp://…
_INLINE_DATA = re.compile(r"^data:", re.I)


def strip_code(text):
    """Blank out fenced blocks and inline code spans, keeping line numbering intact.

    A quotation is not a reference. Lines are replaced by empty ones rather than removed so
    a violation still reports the line number a human can jump to.
    """
    out, in_fence, fence = [], False, ""
    for line in text.splitlines():
        m = re.match(r"^\s*(`{3,}|~{3,})", line)
        if m and (not in_fence or line.strip().startswith(fence)):
            in_fence, fence = (not in_fence), (m.group(1) if not in_fence else "")
            out.append("")
            continue
        out.append("" if in_fence else re.sub(r"`[^`]*`", "", line))
    return out


def image_refs(text):
    """[(line_number, url)] for every image the RENDERED document would request."""
    refs = []
    for n, line in enumerate(strip_code(text), 1):
        for rx in (_MD_IMAGE, _HTML_IMAGE):
            for m in rx.finditer(line):
                refs.append((n, m.group(1).strip()))
    return refs


def tracked_markdown():
    """Every tracked .md path, repo-relative, with a filesystem fallback off a checkout."""
    try:
        out = subprocess.run(["git", "ls-files", "-z", "--", "*.md"],
                             cwd=REPO, capture_output=True, text=True, check=True).stdout
        paths = [p for p in out.split("\0") if p]
        if paths:
            return sorted(paths)
    except (OSError, subprocess.CalledProcessError):
        pass
    paths = []
    skip = {".git", "node_modules", ".venv", "__pycache__", "dist"}
    for dirpath, dirs, names in os.walk(REPO):
        dirs[:] = [d for d in dirs if d not in skip]
        for n in names:
            if n.endswith(".md"):
                paths.append(os.path.relpath(os.path.join(dirpath, n), REPO).replace(os.sep, "/"))
    return sorted(paths)


def read(rel):
    with open(os.path.join(REPO, rel), encoding="utf-8", errors="replace") as fh:
        return fh.read()


def test_the_repo_actually_has_markdown_to_scan():
    """A scanner over an empty list passes every assertion below vacuously."""
    docs = tracked_markdown()
    assert len(docs) > 100, "expected the whole doc tree, got %d files" % len(docs)
    assert "README.md" in docs


def test_no_tracked_markdown_embeds_an_offsite_image():
    """Rule 1 — the violation this file was written for, stated as a test."""
    bad = []
    for rel in tracked_markdown():
        for n, url in image_refs(read(rel)):
            if _OFFSITE.match(url):
                bad.append("%s:%d  %s" % (rel, n, url))
    assert not bad, (
        "off-site image(s) in tracked Markdown — the shipped `img-src 'self' data: blob:` "
        "REFUSES these, so they are broken images on the live site, and they make the "
        "public internet a dependency of every suite that renders the page.\n  " +
        "\n  ".join(bad) +
        "\nFix: commit the image under sim/web/img/ and reference it repo-relative "
        "(see sim/web/img/README.md).")


def test_every_doc_image_resolves_to_a_file_under_the_site_root():
    """Rule 2 — the half that keeps GitHub and the docs explorer showing the same picture."""
    bad = []
    for rel in tracked_markdown():
        if rel.startswith(BUNDLE):
            continue                              # generated copy; checked at its source
        base = os.path.dirname(rel)
        for n, url in image_refs(read(rel)):
            if _OFFSITE.match(url) or _INLINE_DATA.match(url):
                continue                          # rule 1 owns off-site; data: is inline
            target = os.path.normpath(os.path.join(base, url.split("#")[0].split("?")[0]))
            target = target.replace(os.sep, "/")
            if not os.path.isfile(os.path.join(REPO, target)):
                bad.append("%s:%d  %s -> MISSING %s" % (rel, n, url, target))
            elif not target.startswith(SITE_ROOT):
                bad.append("%s:%d  %s -> %s is outside %s, so the docs explorer has no URL "
                           "for it" % (rel, n, url, target, SITE_ROOT))
    assert not bad, "\n  ".join([""] + bad)


_BAD = "https://github.com/user-attachments/assets/00000000-0000-0000-0000-000000000000"


@pytest.mark.parametrize("doc, want", [
    ('<p><img width="712" alt="x" src="%s" /></p>' % _BAD, [_BAD]),
    ("![a markdown one](http://example.invalid/pic.jpg)", ["http://example.invalid/pic.jpg"]),
    ('<img src="img/local.png">', ["img/local.png"]),
    ('```html\n<img src="%s" />\n```\nand inline: `<img src="%s">`' % (_BAD, _BAD), []),
    ('```\nquoted\n```\n<img src="%s">' % _BAD, [_BAD]),
])
def test_the_scanner_finds_references_and_skips_quotations(doc, want):
    assert [u for _n, u in image_refs(doc)] == want
