# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embodied/robotbrain/ContentMetaTags.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'embodied/robotbrain/ContentMetaTags.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from embodied.robotbrain import ContentTags_pb2 as embodied_dot_robotbrain_dot_ContentTags__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)embodied/robotbrain/ContentMetaTags.proto\x12\x13\x65mbodied.robotbrain\x1a%embodied/robotbrain/ContentTags.proto\"d\n\x0c\x43ognitiveTag\x12\x11\n\x04name\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x11\n\x04uuid\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x12\n\x05value\x18\x03 \x01(\x04H\x02\x88\x01\x01\x42\x07\n\x05_nameB\x07\n\x05_uuidB\x08\n\x06_value\"c\n\x0bIntimacyTag\x12\x11\n\x04name\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x11\n\x04uuid\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x12\n\x05order\x18\x03 \x01(\x04H\x02\x88\x01\x01\x42\x07\n\x05_nameB\x07\n\x05_uuidB\x08\n\x06_order\"\xda\x01\n\x0f\x43ontentMetaList\x12\x39\n\x0e\x63ognitive_load\x18\x01 \x03(\x0b\x32!.embodied.robotbrain.CognitiveTag\x12\x38\n\x0eintimacy_level\x18\x02 \x03(\x0b\x32 .embodied.robotbrain.IntimacyTag\x12(\n\x06topics\x18\x03 \x03(\x0b\x32\x18.embodied.robotbrain.Tag\x12(\n\x06genres\x18\x04 \x03(\x0b\x32\x18.embodied.robotbrain.Tagb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embodied.robotbrain.ContentMetaTags_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COGNITIVETAG']._serialized_start=105
  _globals['_COGNITIVETAG']._serialized_end=205
  _globals['_INTIMACYTAG']._serialized_start=207
  _globals['_INTIMACYTAG']._serialized_end=306
  _globals['_CONTENTMETALIST']._serialized_start=309
  _globals['_CONTENTMETALIST']._serialized_end=527
# @@protoc_insertion_point(module_scope)
