# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embodied/robotbrain/Contexts.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'embodied/robotbrain/Contexts.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from embodied.robotbrain import Tags_pb2 as embodied_dot_robotbrain_dot_Tags__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"embodied/robotbrain/Contexts.proto\x12\x13\x65mbodied.robotbrain\x1a\x1e\x65mbodied/robotbrain/Tags.proto\"=\n\x07\x43ontext\x12\x0f\n\x02id\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x11\n\x04text\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\x05\n\x03_idB\x07\n\x05_text\"O\n\rGlobalContext\x12\x32\n\x07\x63ontext\x18\x01 \x01(\x0b\x32\x1c.embodied.robotbrain.ContextH\x00\x88\x01\x01\x42\n\n\x08_context\"T\n\x12\x45nvironmentContext\x12\x32\n\x07\x63ontext\x18\x01 \x01(\x0b\x32\x1c.embodied.robotbrain.ContextH\x00\x88\x01\x01\x42\n\n\x08_context\"\xf9\x01\n\x13\x43onversationContext\x12\x32\n\x07\x63ontext\x18\x01 \x01(\x0b\x32\x1c.embodied.robotbrain.ContextH\x00\x88\x01\x01\x12\x14\n\x0c\x63ontent_tags\x18\x03 \x03(\t\x12\x38\n\x0bgoal_levels\x18\x04 \x03(\x0b\x32#.embodied.robotbrain.tags.GoalLevel\x12\x12\n\nproperties\x18\x05 \x03(\t\x12\x0e\n\x06prompt\x18\x06 \x03(\t\x12\x1b\n\x0eprompt_line_id\x18\x07 \x01(\rH\x01\x88\x01\x01\x42\n\n\x08_contextB\x11\n\x0f_prompt_line_id\"\xf1\x01\n\x08\x43ontexts\x12;\n\x0fglobal_contexts\x18\x01 \x03(\x0b\x32\".embodied.robotbrain.GlobalContext\x12\x45\n\x14\x65nvironment_contexts\x18\x02 \x03(\x0b\x32\'.embodied.robotbrain.EnvironmentContext\x12G\n\x15\x63onversation_contexts\x18\x03 \x03(\x0b\x32(.embodied.robotbrain.ConversationContext\x12\x10\n\x03sha\x18\x04 \x01(\tH\x00\x88\x01\x01\x42\x06\n\x04_shab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embodied.robotbrain.Contexts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONTEXT']._serialized_start=91
  _globals['_CONTEXT']._serialized_end=152
  _globals['_GLOBALCONTEXT']._serialized_start=154
  _globals['_GLOBALCONTEXT']._serialized_end=233
  _globals['_ENVIRONMENTCONTEXT']._serialized_start=235
  _globals['_ENVIRONMENTCONTEXT']._serialized_end=319
  _globals['_CONVERSATIONCONTEXT']._serialized_start=322
  _globals['_CONVERSATIONCONTEXT']._serialized_end=571
  _globals['_CONTEXTS']._serialized_start=574
  _globals['_CONTEXTS']._serialized_end=815
# @@protoc_insertion_point(module_scope)
