# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embodied/robotbrain/ContentTags.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'embodied/robotbrain/ContentTags.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%embodied/robotbrain/ContentTags.proto\x12\x13\x65mbodied.robotbrain\"=\n\x03Tag\x12\x11\n\x04uuid\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x11\n\x04name\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\x07\n\x05_uuidB\x07\n\x05_name\"\x8f\x01\n\nContentTag\x12*\n\x08replaced\x18\x01 \x03(\x0b\x32\x18.embodied.robotbrain.Tag\x12+\n\tfinalized\x18\x02 \x03(\x0b\x32\x18.embodied.robotbrain.Tag\x12(\n\x06review\x18\x03 \x03(\x0b\x32\x18.embodied.robotbrain.Tagb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embodied.robotbrain.ContentTags_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TAG']._serialized_start=62
  _globals['_TAG']._serialized_end=123
  _globals['_CONTENTTAG']._serialized_start=126
  _globals['_CONTENTTAG']._serialized_end=269
# @@protoc_insertion_point(module_scope)
