# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embodied/robotbrain/EventsAndHolidaysTags.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'embodied/robotbrain/EventsAndHolidaysTags.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/embodied/robotbrain/EventsAndHolidaysTags.proto\x12\x1e\x65mbodied.robotbrain.serialized\"R\n\x15\x45ventsAndHolidaysData\x12\x39\n\x08holidays\x18\x01 \x03(\x0b\x32\'.embodied.robotbrain.serialized.Holiday\"\xe5\x01\n\x07Holiday\x12\x16\n\tevent_uid\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x17\n\nholiday_id\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x11\n\x04name\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x10\n\x03tag\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\x11\n\x04uuid\x18\x05 \x01(\tH\x04\x88\x01\x01\x12\x11\n\x04\x64\x61te\x18\x06 \x01(\tH\x05\x88\x01\x01\x12\x13\n\x06region\x18\x07 \x01(\tH\x06\x88\x01\x01\x42\x0c\n\n_event_uidB\r\n\x0b_holiday_idB\x07\n\x05_nameB\x06\n\x04_tagB\x07\n\x05_uuidB\x07\n\x05_dateB\t\n\x07_regionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embodied.robotbrain.EventsAndHolidaysTags_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVENTSANDHOLIDAYSDATA']._serialized_start=83
  _globals['_EVENTSANDHOLIDAYSDATA']._serialized_end=165
  _globals['_HOLIDAY']._serialized_start=168
  _globals['_HOLIDAY']._serialized_end=397
# @@protoc_insertion_point(module_scope)
