# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embodied/robotbrain/Fallback.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'embodied/robotbrain/Fallback.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"embodied/robotbrain/Fallback.proto\x12\x13\x65mbodied.robotbrain\"\x9e\x02\n\x08\x46\x61llback\x12\x12\n\x05topic\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x13\n\x06module\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x16\n\tuserInput\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x16\n\ttimestamp\x18\x04 \x01(\x04H\x03\x88\x01\x01\x12\x19\n\x0c\x66\x61llbackType\x18\x05 \x01(\tH\x04\x88\x01\x01\x12\x1d\n\x10software_version\x18\x64 \x01(\tH\x05\x88\x01\x01\x12\x18\n\x0bmodule_name\x18\x65 \x01(\tH\x06\x88\x01\x01\x42\x08\n\x06_topicB\t\n\x07_moduleB\x0c\n\n_userInputB\x0c\n\n_timestampB\x0f\n\r_fallbackTypeB\x13\n\x11_software_versionB\x0e\n\x0c_module_nameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embodied.robotbrain.Fallback_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FALLBACK']._serialized_start=60
  _globals['_FALLBACK']._serialized_end=346
# @@protoc_insertion_point(module_scope)
