# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embodied/robotbrain/LineStore.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'embodied/robotbrain/LineStore.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#embodied/robotbrain/LineStore.proto\x12\x13\x65mbodied.robotbrain\"\xc6\x01\n\x14LineStoreSerialState\x12G\n\x05lines\x18\x01 \x03(\x0b\x32\x38.embodied.robotbrain.LineStoreSerialState.LineStoreEntry\x1a\x65\n\x0eLineStoreEntry\x12\x11\n\x04name\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x18\n\x0b\x65xpressions\x18\x02 \x01(\rH\x01\x88\x01\x01\x12\r\n\x05masks\x18\x03 \x03(\x04\x42\x07\n\x05_nameB\x0e\n\x0c_expressionsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embodied.robotbrain.LineStore_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LINESTORESERIALSTATE']._serialized_start=61
  _globals['_LINESTORESERIALSTATE']._serialized_end=259
  _globals['_LINESTORESERIALSTATE_LINESTOREENTRY']._serialized_start=158
  _globals['_LINESTORESERIALSTATE_LINESTOREENTRY']._serialized_end=259
# @@protoc_insertion_point(module_scope)
