# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embodied/robotbrain/MentorBehavior.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'embodied/robotbrain/MentorBehavior.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(embodied/robotbrain/MentorBehavior.proto\x12\x13\x65mbodied.robotbrain\"\xc7\x03\n\x0eMentorBehavior\x12\x16\n\tmodule_id\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x17\n\ncontent_id\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x18\n\x0b\x63ontent_day\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x16\n\ttimestamp\x18\x04 \x01(\x04H\x03\x88\x01\x01\x12\x36\n\x06\x61\x63tion\x18\x05 \x01(\x0e\x32!.embodied.robotbrain.MentorActionH\x04\x88\x01\x01\x12\x18\n\x0binstance_id\x18\x06 \x01(\x04H\x05\x88\x01\x01\x12;\n\x0c\x65nded_reason\x18\x07 \x01(\x0e\x32 .embodied.robotbrain.EndedReasonH\x06\x88\x01\x01\x12\x1d\n\x10software_version\x18\x64 \x01(\tH\x07\x88\x01\x01\x12\x18\n\x0bmodule_name\x18\x65 \x01(\tH\x08\x88\x01\x01\x42\x0c\n\n_module_idB\r\n\x0b_content_idB\x0e\n\x0c_content_dayB\x0c\n\n_timestampB\t\n\x07_actionB\x0e\n\x0c_instance_idB\x0f\n\r_ended_reasonB\x13\n\x11_software_versionB\x0e\n\x0c_module_name\"R\n\x11MentorBehaviorSet\x12=\n\x10mentor_behaviors\x18\x01 \x03(\x0b\x32#.embodied.robotbrain.MentorBehavior*}\n\x0cMentorAction\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x08\n\x04QUIT\x10\x01\x12\x0b\n\x07REFUSED\x10\x02\x12\r\n\tCOMPLETED\x10\x03\x12\r\n\tREQUESTED\x10\x04\x12\r\n\tPRESENTED\x10\x05\x12\r\n\tSCHEDULED\x10\x06\x12\r\n\tSUGGESTED\x10\x07*\xc3\x01\n\x0b\x45ndedReason\x12\x12\n\x0eREASON_UNKNOWN\x10\x00\x12\r\n\tUSER_QUIT\x10\x01\x12\x13\n\x0fUSER_DISENGAGED\x10\x02\x12\x14\n\x10MOXIE_DISENGAGED\x10\x03\x12\x10\n\x0cUSER_REQUEST\x10\x04\x12\x0e\n\nTIME_LIMIT\x10\x05\x12\x0f\n\x0bMOXIE_ENDED\x10\x06\x12\x0e\n\nUSER_SLEPT\x10\x07\x12\x11\n\rREMOTE_LAUNCH\x10\x08\x12\x10\n\x0cREMOTE_ABORT\x10\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embodied.robotbrain.MentorBehavior_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MENTORACTION']._serialized_start=607
  _globals['_MENTORACTION']._serialized_end=732
  _globals['_ENDEDREASON']._serialized_start=735
  _globals['_ENDEDREASON']._serialized_end=930
  _globals['_MENTORBEHAVIOR']._serialized_start=66
  _globals['_MENTORBEHAVIOR']._serialized_end=521
  _globals['_MENTORBEHAVIORSET']._serialized_start=523
  _globals['_MENTORBEHAVIORSET']._serialized_end=605
# @@protoc_insertion_point(module_scope)
