# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embodied/robotbrain/ModuleTag.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'embodied/robotbrain/ModuleTag.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from embodied.robotbrain import Tags_pb2 as embodied_dot_robotbrain_dot_Tags__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#embodied/robotbrain/ModuleTag.proto\x12\x13\x65mbodied.robotbrain\x1a\x1e\x65mbodied/robotbrain/Tags.proto\"H\n\rModuleTagInfo\x12\x37\n\x0bmodule_tags\x18\x01 \x03(\x0b\x32\".embodied.robotbrain.ModuleTagData\"\xea\x02\n\rModuleTagData\x12\x12\n\x05_uuid\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x17\n\n_module_id\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x19\n\x0c_module_name\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x36\n\x0c_index_table\x18\x08 \x03(\x0b\x32 .embodied.robotbrain.ContentInfo\x12\x36\n\t_sel_tags\x18\t \x03(\x0b\x32#.embodied.robotbrain.tags.GoalLevel\x12\x35\n\r_content_tags\x18\n \x03(\x0b\x32\x1e.embodied.robotbrain.ModuleTag\x12$\n\x17_does_report_completion\x18\x0b \x01(\x08H\x03\x88\x01\x01\x42\x08\n\x06X_uuidB\r\n\x0bX_module_idB\x0f\n\rX_module_nameB\x1a\n\x18X_does_report_completion\"Y\n\tModuleTag\x12\x15\n\x08tag_uuid\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x18\n\x0bsource_uuid\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\x0b\n\t_tag_uuidB\x0e\n\x0c_source_uuid\"\x7f\n\x0b\x43ontentInfo\x12\x18\n\x0b_content_id\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x38\n\t_csv_dict\x18\x02 \x01(\x0b\x32 .embodied.robotbrain.ContentDataH\x01\x88\x01\x01\x42\x0e\n\x0cX_content_idB\x0c\n\nX_csv_dict\"y\n\x0b\x43ontentData\x12\x11\n\x04UUID\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x19\n\x0c\x63ontent_tags\x18\x0b \x01(\tH\x01\x88\x01\x01\x12\x15\n\x08sel_tags\x18\x0c \x01(\tH\x02\x88\x01\x01\x42\x07\n\x05_UUIDB\x0f\n\r_content_tagsB\x0b\n\t_sel_tagsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embodied.robotbrain.ModuleTag_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODULETAGINFO']._serialized_start=92
  _globals['_MODULETAGINFO']._serialized_end=164
  _globals['_MODULETAGDATA']._serialized_start=167
  _globals['_MODULETAGDATA']._serialized_end=529
  _globals['_MODULETAG']._serialized_start=531
  _globals['_MODULETAG']._serialized_end=620
  _globals['_CONTENTINFO']._serialized_start=622
  _globals['_CONTENTINFO']._serialized_end=749
  _globals['_CONTENTDATA']._serialized_start=751
  _globals['_CONTENTDATA']._serialized_end=872
# @@protoc_insertion_point(module_scope)
