# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embodied/robotbrain/PhraseHints.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'embodied/robotbrain/PhraseHints.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%embodied/robotbrain/PhraseHints.proto\x12\x13\x65mbodied.robotbrain\"\xc0\x01\n\x0bPhraseHints\x12\x13\n\x06module\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\r\n\x05hints\x18\x02 \x03(\t\x12\x16\n\ttimestamp\x18\x03 \x01(\x04H\x01\x88\x01\x01\x12\x1d\n\x10software_version\x18\x64 \x01(\tH\x02\x88\x01\x01\x12\x18\n\x0bmodule_name\x18\x65 \x01(\tH\x03\x88\x01\x01\x42\t\n\x07_moduleB\x0c\n\n_timestampB\x13\n\x11_software_versionB\x0e\n\x0c_module_name\"\x9e\x01\n\tNameHints\x12\r\n\x05names\x18\x01 \x03(\t\x12\x16\n\ttimestamp\x18\x02 \x01(\x04H\x00\x88\x01\x01\x12\x1d\n\x10software_version\x18\x64 \x01(\tH\x01\x88\x01\x01\x12\x18\n\x0bmodule_name\x18\x65 \x01(\tH\x02\x88\x01\x01\x42\x0c\n\n_timestampB\x13\n\x11_software_versionB\x0e\n\x0c_module_name\">\n\x0bNativeHints\x12/\n\x05hints\x18\x01 \x03(\x0b\x32 .embodied.robotbrain.PhraseHintsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embodied.robotbrain.PhraseHints_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PHRASEHINTS']._serialized_start=63
  _globals['_PHRASEHINTS']._serialized_end=255
  _globals['_NAMEHINTS']._serialized_start=258
  _globals['_NAMEHINTS']._serialized_end=416
  _globals['_NATIVEHINTS']._serialized_start=418
  _globals['_NATIVEHINTS']._serialized_end=480
# @@protoc_insertion_point(module_scope)
