# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embodied/robotbrain/RemoteResponseData.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'embodied/robotbrain/RemoteResponseData.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,embodied/robotbrain/RemoteResponseData.proto\x12\x13\x65mbodied.robotbrain\"\xee\x03\n\x12RemoteResponseData\x12\x18\n\x0binstance_id\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12#\n\x16positive_emotion_score\x18\x02 \x01(\x02H\x01\x88\x01\x01\x12#\n\x16negative_emotion_score\x18\x03 \x01(\x02H\x02\x88\x01\x01\x12(\n\x1b\x64ialog_act_engagement_score\x18\x04 \x01(\x02H\x03\x88\x01\x01\x12%\n\x18positive_sentiment_score\x18\x05 \x01(\x02H\x04\x88\x01\x01\x12%\n\x18negative_sentiment_score\x18\x06 \x01(\x02H\x05\x88\x01\x01\x12\x1d\n\x10software_version\x18\x64 \x01(\tH\x06\x88\x01\x01\x12\x18\n\x0bmodule_name\x18\x65 \x01(\tH\x07\x88\x01\x01\x42\x0e\n\x0c_instance_idB\x19\n\x17_positive_emotion_scoreB\x19\n\x17_negative_emotion_scoreB\x1e\n\x1c_dialog_act_engagement_scoreB\x1b\n\x19_positive_sentiment_scoreB\x1b\n\x19_negative_sentiment_scoreB\x13\n\x11_software_versionB\x0e\n\x0c_module_nameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embodied.robotbrain.RemoteResponseData_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REMOTERESPONSEDATA']._serialized_start=70
  _globals['_REMOTERESPONSEDATA']._serialized_end=564
# @@protoc_insertion_point(module_scope)
