# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embodied/robotbrain/SessionState.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'embodied/robotbrain/SessionState.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from embodied.logging import Log_pb2 as embodied_dot_logging_dot_Log__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&embodied/robotbrain/SessionState.proto\x12\x13\x65mbodied.robotbrain\x1a\x1a\x65mbodied/logging/Log.proto\"\x89\x01\n\x0bSessionUser\x12\x15\n\x08user_age\x18\x01 \x01(\rH\x00\x88\x01\x01\x12\x19\n\x0cnum_children\x18\x02 \x01(\rH\x01\x88\x01\x01\x12\x19\n\x0cmax_children\x18\x03 \x01(\rH\x02\x88\x01\x01\x42\x0b\n\t_user_ageB\x0f\n\r_num_childrenB\x0f\n\r_max_children\"\x9a\x04\n\x0cSessionState\x12\x16\n\tinSession\x18\x01 \x01(\x08H\x00\x88\x01\x01\x12\x16\n\ttimestamp\x18\x02 \x01(\x04H\x01\x88\x01\x01\x12\x46\n\x0brecord_mode\x18\x03 \x01(\x0e\x32,.embodied.robotbrain.SessionState.RecordModeH\x02\x88\x01\x01\x12\x33\n\x04user\x18\x04 \x01(\x0b\x32 .embodied.robotbrain.SessionUserH\x03\x88\x01\x01\x12\x1d\n\x10outSessionReason\x18\x05 \x01(\tH\x04\x88\x01\x01\x12\x37\n\x08settings\x18\x06 \x01(\x0b\x32 .embodied.logging.DeviceSettingsH\x05\x88\x01\x01\x12\x18\n\x0bprev_active\x18\x07 \x01(\x08H\x06\x88\x01\x01\x12\x1d\n\x10software_version\x18\x64 \x01(\tH\x07\x88\x01\x01\x12\x18\n\x0bmodule_name\x18\x65 \x01(\tH\x08\x88\x01\x01\"&\n\nRecordMode\x12\n\n\x06NORMAL\x10\x00\x12\x0c\n\x08\x45XTENDED\x10\x01\x42\x0c\n\n_inSessionB\x0c\n\n_timestampB\x0e\n\x0c_record_modeB\x07\n\x05_userB\x13\n\x11_outSessionReasonB\x0b\n\t_settingsB\x0e\n\x0c_prev_activeB\x13\n\x11_software_versionB\x0e\n\x0c_module_nameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embodied.robotbrain.SessionState_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SESSIONUSER']._serialized_start=92
  _globals['_SESSIONUSER']._serialized_end=229
  _globals['_SESSIONSTATE']._serialized_start=232
  _globals['_SESSIONSTATE']._serialized_end=770
  _globals['_SESSIONSTATE_RECORDMODE']._serialized_start=592
  _globals['_SESSIONSTATE_RECORDMODE']._serialized_end=630
# @@protoc_insertion_point(module_scope)
