# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embodied/robotbrain/Tags.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'embodied/robotbrain/Tags.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x65mbodied/robotbrain/Tags.proto\x12\x18\x65mbodied.robotbrain.tags\"=\n\x03Tag\x12\x11\n\x04uuid\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x11\n\x04name\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\x07\n\x05_uuidB\x07\n\x05_name\"E\n\tGoalLevel\x12\x11\n\x04goal\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x12\n\x05level\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\x07\n\x05_goalB\x08\n\x06_level\"|\n\x06Weight\x12\x17\n\nparentUUID\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x16\n\tchildUUID\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x16\n\tweighting\x18\x03 \x01(\x02H\x02\x88\x01\x01\x42\r\n\x0b_parentUUIDB\x0c\n\n_childUUIDB\x0c\n\n_weighting\"\x81\x03\n\nSELTagInfo\x12/\n\x08\x61llGoals\x18\x01 \x03(\x0b\x32\x1d.embodied.robotbrain.tags.Tag\x12\x30\n\tallLevels\x18\x02 \x03(\x0b\x32\x1d.embodied.robotbrain.tags.Tag\x12\x30\n\tallSkills\x18\x03 \x03(\x0b\x32\x1d.embodied.robotbrain.tags.Tag\x12\x31\n\nallPillars\x18\x04 \x03(\x0b\x32\x1d.embodied.robotbrain.tags.Tag\x12\x37\n\rgoalsToLevels\x18\x05 \x03(\x0b\x32 .embodied.robotbrain.tags.Weight\x12\x37\n\rskillsToGoals\x18\x06 \x03(\x0b\x32 .embodied.robotbrain.tags.Weight\x12\x39\n\x0fpillarsToSkills\x18\x07 \x03(\x0b\x32 .embodied.robotbrain.tags.Weightb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embodied.robotbrain.Tags_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TAG']._serialized_start=60
  _globals['_TAG']._serialized_end=121
  _globals['_GOALLEVEL']._serialized_start=123
  _globals['_GOALLEVEL']._serialized_end=192
  _globals['_WEIGHT']._serialized_start=194
  _globals['_WEIGHT']._serialized_end=318
  _globals['_SELTAGINFO']._serialized_start=321
  _globals['_SELTAGINFO']._serialized_end=706
# @@protoc_insertion_point(module_scope)
