# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embodied/robotbrain/TopicChange.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'embodied/robotbrain/TopicChange.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%embodied/robotbrain/TopicChange.proto\x12\x13\x65mbodied.robotbrain\"\xcd\x02\n\x0bTopicChange\x12\x11\n\x04user\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x10\n\x03\x62ot\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x15\n\x08newTopic\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x16\n\ttimestamp\x18\x04 \x01(\x04H\x03\x88\x01\x01\x12\x1a\n\rcurrentModule\x18\x05 \x01(\tH\x04\x88\x01\x01\x12\x1d\n\x10\x63urrentContentID\x18\x06 \x01(\tH\x05\x88\x01\x01\x12\x1d\n\x10software_version\x18\x64 \x01(\tH\x06\x88\x01\x01\x12\x18\n\x0bmodule_name\x18\x65 \x01(\tH\x07\x88\x01\x01\x42\x07\n\x05_userB\x06\n\x04_botB\x0b\n\t_newTopicB\x0c\n\n_timestampB\x10\n\x0e_currentModuleB\x13\n\x11_currentContentIDB\x13\n\x11_software_versionB\x0e\n\x0c_module_nameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embodied.robotbrain.TopicChange_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TOPICCHANGE']._serialized_start=63
  _globals['_TOPICCHANGE']._serialized_end=396
# @@protoc_insertion_point(module_scope)
