# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embodied/robotbrain/UserRecognition.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'embodied/robotbrain/UserRecognition.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)embodied/robotbrain/UserRecognition.proto\x12\x13\x65mbodied.robotbrain\"\xc4\x02\n\x0eLearnUserState\x12\x16\n\ttimestamp\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12\x11\n\x04name\x18\x02 \x01(\tH\x01\x88\x01\x01\x12=\n\x05state\x18\x03 \x01(\x0e\x32).embodied.robotbrain.LearnUserState.StateH\x02\x88\x01\x01\x12\x0f\n\x02id\x18\x04 \x01(\x03H\x03\x88\x01\x01\x12\x1d\n\x10software_version\x18\x64 \x01(\tH\x04\x88\x01\x01\x12\x18\n\x0bmodule_name\x18\x65 \x01(\tH\x05\x88\x01\x01\"1\n\x05State\x12\x0c\n\x08STARTING\x10\x00\x12\x0c\n\x08LEARNING\x10\x01\x12\x0c\n\x08\x46INISHED\x10\x02\x42\x0c\n\n_timestampB\x07\n\x05_nameB\x08\n\x06_stateB\x05\n\x03_idB\x13\n\x11_software_versionB\x0e\n\x0c_module_nameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embodied.robotbrain.UserRecognition_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LEARNUSERSTATE']._serialized_start=67
  _globals['_LEARNUSERSTATE']._serialized_end=391
  _globals['_LEARNUSERSTATE_STATE']._serialized_start=265
  _globals['_LEARNUSERSTATE_STATE']._serialized_end=314
# @@protoc_insertion_point(module_scope)
