# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embodied/testing/Fusion.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'embodied/testing/Fusion.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from embodied.perception.fusion import FusedPeople_pb2 as embodied_dot_perception_dot_fusion_dot_FusedPeople__pb2
from embodied.unity import RobotPosition_pb2 as embodied_dot_unity_dot_RobotPosition__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x65mbodied/testing/Fusion.proto\x12\x10\x65mbodied.testing\x1a,embodied/perception/fusion/FusedPeople.proto\x1a\"embodied/unity/RobotPosition.proto\"\x96\x03\n\x12InitialFusionState\x12\x16\n\ttimestamp\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12>\n\x06people\x18\x32 \x01(\x0b\x32).embodied.perception.fusion.FusedPeoplePBH\x01\x88\x01\x01\x12\x14\n\x07next_id\x18\x33 \x01(\x04H\x02\x88\x01\x01\x12\x1e\n\x11robot_is_speaking\x18\x64 \x01(\x08H\x03\x88\x01\x01\x12:\n\x0erobot_position\x18\x65 \x01(\x0b\x32\x1d.embodied.unity.RobotPositionH\x04\x88\x01\x01\x12\x1e\n\x10user_is_targeted\x18\x96\x01 \x01(\x08H\x05\x88\x01\x01\x12\x1e\n\x10targeted_user_id\x18\x97\x01 \x01(\x04H\x06\x88\x01\x01\x42\x0c\n\n_timestampB\t\n\x07_peopleB\n\n\x08_next_idB\x14\n\x12_robot_is_speakingB\x11\n\x0f_robot_positionB\x13\n\x11_user_is_targetedB\x13\n\x11_targeted_user_idb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embodied.testing.Fusion_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INITIALFUSIONSTATE']._serialized_start=134
  _globals['_INITIALFUSIONSTATE']._serialized_end=540
# @@protoc_insertion_point(module_scope)
