# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embodied/testing/Vision.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'embodied/testing/Vision.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x65mbodied/testing/Vision.proto\x12\x10\x65mbodied.testing\"3\n\x05Point\x12\x0e\n\x01x\x18\x01 \x01(\x02H\x00\x88\x01\x01\x12\x0e\n\x01y\x18\x02 \x01(\x02H\x01\x88\x01\x01\x42\x04\n\x02_xB\x04\n\x02_y\"\x87\x04\n\x0e\x46\x61\x63\x65\x44\x65scriptor\x12,\n\x06\x63\x65nter\x18\x01 \x01(\x0b\x32\x17.embodied.testing.PointH\x00\x88\x01\x01\x12\x0e\n\x01w\x18\x02 \x01(\x02H\x01\x88\x01\x01\x12\x0e\n\x01h\x18\x03 \x01(\x02H\x02\x88\x01\x01\x12\x12\n\x05pitch\x18\x04 \x01(\x02H\x03\x88\x01\x01\x12\x10\n\x03yaw\x18\x05 \x01(\x02H\x04\x88\x01\x01\x12\x11\n\x04roll\x18\x06 \x01(\x02H\x05\x88\x01\x01\x12\x11\n\x04\x62lur\x18\x07 \x01(\x02H\x06\x88\x01\x01\x12.\n\x08left_eye\x18\x08 \x01(\x0b\x32\x17.embodied.testing.PointH\x07\x88\x01\x01\x12/\n\tright_eye\x18\t \x01(\x0b\x32\x17.embodied.testing.PointH\x08\x88\x01\x01\x12*\n\x04\x63hin\x18\n \x01(\x0b\x32\x17.embodied.testing.PointH\t\x88\x01\x01\x12\x13\n\x0b\x64\x65scriptors\x18\x0b \x03(\x02\x12\x12\n\x05image\x18\x0c \x01(\tH\n\x88\x01\x01\x12\x0f\n\x02id\x18\r \x01(\x04H\x0b\x88\x01\x01\x12\x16\n\tocclusion\x18\x0e \x01(\x02H\x0c\x88\x01\x01\x42\t\n\x07_centerB\x04\n\x02_wB\x04\n\x02_hB\x08\n\x06_pitchB\x06\n\x04_yawB\x07\n\x05_rollB\x07\n\x05_blurB\x0b\n\t_left_eyeB\x0c\n\n_right_eyeB\x07\n\x05_chinB\x08\n\x06_imageB\x05\n\x03_idB\x0c\n\n_occlusion\"\x8c\x01\n\x0f\x46\x61\x63\x65\x44\x65scriptors\x12\x16\n\ttimestamp\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12\x15\n\x08\x66rame_id\x18\x02 \x01(\x04H\x01\x88\x01\x01\x12/\n\x05\x66\x61\x63\x65s\x18\x03 \x03(\x0b\x32 .embodied.testing.FaceDescriptorB\x0c\n\n_timestampB\x0b\n\t_frame_idb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embodied.testing.Vision_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POINT']._serialized_start=51
  _globals['_POINT']._serialized_end=102
  _globals['_FACEDESCRIPTOR']._serialized_start=105
  _globals['_FACEDESCRIPTOR']._serialized_end=624
  _globals['_FACEDESCRIPTORS']._serialized_start=627
  _globals['_FACEDESCRIPTORS']._serialized_end=767
# @@protoc_insertion_point(module_scope)
