# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embodied/perception/audio/GoogleAccount.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'embodied/perception/audio/GoogleAccount.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-embodied/perception/audio/GoogleAccount.proto\x12\x19\x65mbodied.perception.audio\"\x95\x01\n\rGoogleAccount\x12\x17\n\nproject_id\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x1d\n\x10software_version\x18\x64 \x01(\tH\x01\x88\x01\x01\x12\x18\n\x0bmodule_name\x18\x65 \x01(\tH\x02\x88\x01\x01\x42\r\n\x0b_project_idB\x13\n\x11_software_versionB\x0e\n\x0c_module_nameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embodied.perception.audio.GoogleAccount_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GOOGLEACCOUNT']._serialized_start=77
  _globals['_GOOGLEACCOUNT']._serialized_end=226
# @@protoc_insertion_point(module_scope)
