# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embodied/perception/audio/Speaker.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'embodied/perception/audio/Speaker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'embodied/perception/audio/Speaker.proto\x12\x19\x65mbodied.perception.audio\"\x87\x02\n\x07Speaker\x12\x0f\n\x02id\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x10\n\x03\x64oa\x18\x02 \x01(\x02H\x01\x88\x01\x01\x12\x1a\n\rid_confidence\x18\x03 \x01(\x02H\x02\x88\x01\x01\x12\x16\n\ttimestamp\x18\x04 \x01(\x04H\x03\x88\x01\x01\x12\x18\n\x10\x64oa_observations\x18\x05 \x03(\x02\x12\x1d\n\x10software_version\x18\x64 \x01(\tH\x04\x88\x01\x01\x12\x18\n\x0bmodule_name\x18\x65 \x01(\tH\x05\x88\x01\x01\x42\x05\n\x03_idB\x06\n\x04_doaB\x10\n\x0e_id_confidenceB\x0c\n\n_timestampB\x13\n\x11_software_versionB\x0e\n\x0c_module_name\"\xa1\x02\n\x0f\x45nrollmentState\x12\x0f\n\x02id\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x44\n\x05state\x18\x02 \x01(\x0e\x32\x30.embodied.perception.audio.EnrollmentState.StateH\x01\x88\x01\x01\x12\x16\n\ttimestamp\x18\x03 \x01(\x04H\x02\x88\x01\x01\x12\x1d\n\x10software_version\x18\x64 \x01(\tH\x03\x88\x01\x01\x12\x18\n\x0bmodule_name\x18\x65 \x01(\tH\x04\x88\x01\x01\"\"\n\x05State\x12\x0b\n\x07STARTED\x10\x00\x12\x0c\n\x08\x46INISHED\x10\x01\x42\x05\n\x03_idB\x08\n\x06_stateB\x0c\n\n_timestampB\x13\n\x11_software_versionB\x0e\n\x0c_module_nameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embodied.perception.audio.Speaker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SPEAKER']._serialized_start=71
  _globals['_SPEAKER']._serialized_end=334
  _globals['_ENROLLMENTSTATE']._serialized_start=337
  _globals['_ENROLLMENTSTATE']._serialized_end=626
  _globals['_ENROLLMENTSTATE_STATE']._serialized_start=524
  _globals['_ENROLLMENTSTATE_STATE']._serialized_end=558
# @@protoc_insertion_point(module_scope)
