# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embodied/perception/audio/Speech.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'embodied/perception/audio/Speech.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from embodied.perception.audio import Speaker_pb2 as embodied_dot_perception_dot_audio_dot_Speaker__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&embodied/perception/audio/Speech.proto\x12\x19\x65mbodied.perception.audio\x1a\'embodied/perception/audio/Speaker.proto\"\xb8\x02\n\x12SpeechStateChanged\x12!\n\x14timestamp_deprecated\x18\x01 \x01(\x03H\x00\x88\x01\x01\x12\x12\n\x05state\x18\x02 \x01(\x08H\x01\x88\x01\x01\x12\x38\n\x07speaker\x18\x03 \x01(\x0b\x32\".embodied.perception.audio.SpeakerH\x02\x88\x01\x01\x12\x16\n\ttimestamp\x18\x04 \x01(\x04H\x03\x88\x01\x01\x12\x1d\n\x10software_version\x18\x64 \x01(\tH\x04\x88\x01\x01\x12\x18\n\x0bmodule_name\x18\x65 \x01(\tH\x05\x88\x01\x01\x42\x17\n\x15_timestamp_deprecatedB\x08\n\x06_stateB\n\n\x08_speakerB\x0c\n\n_timestampB\x13\n\x11_software_versionB\x0e\n\x0c_module_name\"\xd2\x02\n\rVoiceActivity\x12\x16\n\ttimestamp\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12O\n\x05state\x18\n \x01(\x0e\x32;.embodied.perception.audio.VoiceActivity.VoiceActivityStateH\x01\x88\x01\x01\x12\x0b\n\x03\x64oa\x18\x0b \x03(\x05\x12\x1d\n\x10software_version\x18\x64 \x01(\tH\x02\x88\x01\x01\x12\x18\n\x0bmodule_name\x18\x65 \x01(\tH\x03\x88\x01\x01\"U\n\x12VoiceActivityState\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x13\n\x0fSTART_OF_SPEECH\x10\x01\x12\n\n\x06SPEECH\x10\x02\x12\x11\n\rEND_OF_SPEECH\x10\x03\x42\x0c\n\n_timestampB\x08\n\x06_stateB\x13\n\x11_software_versionB\x0e\n\x0c_module_nameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embodied.perception.audio.Speech_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SPEECHSTATECHANGED']._serialized_start=111
  _globals['_SPEECHSTATECHANGED']._serialized_end=423
  _globals['_VOICEACTIVITY']._serialized_start=426
  _globals['_VOICEACTIVITY']._serialized_end=764
  _globals['_VOICEACTIVITY_VOICEACTIVITYSTATE']._serialized_start=618
  _globals['_VOICEACTIVITY_VOICEACTIVITYSTATE']._serialized_end=703
# @@protoc_insertion_point(module_scope)
