# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embodied/perception/vision/DrawId.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'embodied/perception/vision/DrawId.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'embodied/perception/vision/DrawId.proto\x12\x1a\x65mbodied.perception.vision\"\xfa\x01\n\x08\x44rawIdPB\x12\x15\n\x08\x64rawname\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x16\n\ttimestamp\x18\x02 \x01(\x04H\x01\x88\x01\x01\x12\x15\n\x08\x63\x65nter_x\x18\x03 \x01(\rH\x02\x88\x01\x01\x12\x15\n\x08\x63\x65nter_y\x18\x04 \x01(\rH\x03\x88\x01\x01\x12\x1d\n\x10software_version\x18\x64 \x01(\tH\x04\x88\x01\x01\x12\x18\n\x0bmodule_name\x18\x65 \x01(\tH\x05\x88\x01\x01\x42\x0b\n\t_drawnameB\x0c\n\n_timestampB\x0b\n\t_center_xB\x0b\n\t_center_yB\x13\n\x11_software_versionB\x0e\n\x0c_module_nameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embodied.perception.vision.DrawId_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DRAWIDPB']._serialized_start=72
  _globals['_DRAWIDPB']._serialized_end=322
# @@protoc_insertion_point(module_scope)
