# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embodied/perception/vision/Face.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'embodied/perception/vision/Face.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%embodied/perception/vision/Face.proto\x12\x1a\x65mbodied.perception.vision\"\xe4\x04\n\x04\x46\x61\x63\x65\x12\x15\n\x08\x63\x65ntre_x\x18\x01 \x01(\x02H\x00\x88\x01\x01\x12\x15\n\x08\x63\x65ntre_y\x18\x02 \x01(\x02H\x01\x88\x01\x01\x12\x15\n\x08\x63\x65ntre_z\x18\x03 \x01(\x02H\x02\x88\x01\x01\x12\x13\n\x06pose_r\x18\x04 \x01(\x02H\x03\x88\x01\x01\x12\x13\n\x06pose_p\x18\x05 \x01(\x02H\x04\x88\x01\x01\x12\x13\n\x06pose_y\x18\x06 \x01(\x02H\x05\x88\x01\x01\x12\x15\n\x08\x64istance\x18\x07 \x01(\x02H\x06\x88\x01\x01\x12\x0f\n\x02id\x18\x08 \x01(\tH\x07\x88\x01\x01\x12\x14\n\x07\x65motion\x18\t \x01(\x04H\x08\x88\x01\x01\x12\x1a\n\remotion_proba\x18\n \x01(\x02H\t\x88\x01\x01\x12\x18\n\x0b\x61\x63tion_unit\x18\x0b \x01(\x04H\n\x88\x01\x01\x12\x1e\n\x11\x61\x63tion_unit_proba\x18\x0c \x01(\x02H\x0b\x88\x01\x01\x12\x16\n\ttimestamp\x18\r \x01(\x04H\x0c\x88\x01\x01\x12\x14\n\x07gesture\x18\x0e \x01(\tH\r\x88\x01\x01\x12\x1d\n\x10software_version\x18\x64 \x01(\tH\x0e\x88\x01\x01\x12\x18\n\x0bmodule_name\x18\x65 \x01(\tH\x0f\x88\x01\x01\x42\x0b\n\t_centre_xB\x0b\n\t_centre_yB\x0b\n\t_centre_zB\t\n\x07_pose_rB\t\n\x07_pose_pB\t\n\x07_pose_yB\x0b\n\t_distanceB\x05\n\x03_idB\n\n\x08_emotionB\x10\n\x0e_emotion_probaB\x0e\n\x0c_action_unitB\x14\n\x12_action_unit_probaB\x0c\n\n_timestampB\n\n\x08_gestureB\x13\n\x11_software_versionB\x0e\n\x0c_module_nameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embodied.perception.vision.Face_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FACE']._serialized_start=70
  _globals['_FACE']._serialized_end=682
# @@protoc_insertion_point(module_scope)
