# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embodied/perception/vision/FaceIDEnrollment.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'embodied/perception/vision/FaceIDEnrollment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1embodied/perception/vision/FaceIDEnrollment.proto\x12\x1a\x65mbodied.perception.vision\"\x89\x03\n\x15\x46\x61\x63\x65IDEnrollmentState\x12\x0f\n\x02id\x18\x01 \x01(\tH\x00\x88\x01\x01\x12K\n\x05state\x18\x02 \x01(\x0e\x32\x37.embodied.perception.vision.FaceIDEnrollmentState.StateH\x01\x88\x01\x01\x12\x12\n\x05\x65rror\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x16\n\ttimestamp\x18\x04 \x01(\x04H\x03\x88\x01\x01\x12\x15\n\x08\x66rame_id\x18\x05 \x01(\x04H\x04\x88\x01\x01\x12\x1d\n\x10software_version\x18\x64 \x01(\tH\x05\x88\x01\x01\x12\x18\n\x0bmodule_name\x18\x65 \x01(\tH\x06\x88\x01\x01\";\n\x05State\x12\x0b\n\x07STARTED\x10\x00\x12\x0c\n\x08\x46INISHED\x10\x01\x12\n\n\x06\x46\x41ILED\x10\x03\x12\x0b\n\x07SKIPPED\x10\x04\x42\x05\n\x03_idB\x08\n\x06_stateB\x08\n\x06_errorB\x0c\n\n_timestampB\x0b\n\t_frame_idB\x13\n\x11_software_versionB\x0e\n\x0c_module_name\"p\n\x14\x46\x61\x63\x65IDEnrollmentInfo\x12\x11\n\x04uuid\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\"\n\x15number_of_enrollments\x18\x02 \x01(\x04H\x01\x88\x01\x01\x42\x07\n\x05_uuidB\x18\n\x16_number_of_enrollments\"\xe2\x01\n\x15\x46\x61\x63\x65IDEnrollmentsInfo\x12\x16\n\ttimestamp\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12\x45\n\x0b\x65nrollments\x18\x02 \x03(\x0b\x32\x30.embodied.perception.vision.FaceIDEnrollmentInfo\x12\x1d\n\x10software_version\x18\x64 \x01(\tH\x01\x88\x01\x01\x12\x18\n\x0bmodule_name\x18\x65 \x01(\tH\x02\x88\x01\x01\x42\x0c\n\n_timestampB\x13\n\x11_software_versionB\x0e\n\x0c_module_nameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embodied.perception.vision.FaceIDEnrollment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FACEIDENROLLMENTSTATE']._serialized_start=82
  _globals['_FACEIDENROLLMENTSTATE']._serialized_end=475
  _globals['_FACEIDENROLLMENTSTATE_STATE']._serialized_start=325
  _globals['_FACEIDENROLLMENTSTATE_STATE']._serialized_end=384
  _globals['_FACEIDENROLLMENTINFO']._serialized_start=477
  _globals['_FACEIDENROLLMENTINFO']._serialized_end=589
  _globals['_FACEIDENROLLMENTSINFO']._serialized_start=592
  _globals['_FACEIDENROLLMENTSINFO']._serialized_end=818
# @@protoc_insertion_point(module_scope)
