# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embodied/perception/vision/ImageToText.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'embodied/perception/vision/ImageToText.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,embodied/perception/vision/ImageToText.proto\x12\x1a\x65mbodied.perception.vision\"\xc1\x04\n\rImageToTextPB\x12\x15\n\x08question\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x13\n\x06prompt\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x18\n\x0b\x64\x65scription\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x17\n\nsession_id\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\x16\n\ttimestamp\x18\x05 \x01(\x04H\x04\x88\x01\x01\x12\x15\n\x08\x66rame_id\x18\x06 \x01(\x04H\x05\x88\x01\x01\x12\x1b\n\x0etargeted_width\x18\x07 \x01(\x02H\x06\x88\x01\x01\x12\x1c\n\x0ftargeted_height\x18\x08 \x01(\x02H\x07\x88\x01\x01\x12\x1e\n\x11targeted_center_x\x18\t \x01(\x02H\x08\x88\x01\x01\x12\x1e\n\x11targeted_center_y\x18\n \x01(\x02H\t\x88\x01\x01\x12\x16\n\tis_mentor\x18\x0b \x01(\x08H\n\x88\x01\x01\x12\x1d\n\x10software_version\x18\x64 \x01(\tH\x0b\x88\x01\x01\x12\x18\n\x0bmodule_name\x18\x65 \x01(\tH\x0c\x88\x01\x01\x42\x0b\n\t_questionB\t\n\x07_promptB\x0e\n\x0c_descriptionB\r\n\x0b_session_idB\x0c\n\n_timestampB\x0b\n\t_frame_idB\x11\n\x0f_targeted_widthB\x12\n\x10_targeted_heightB\x14\n\x12_targeted_center_xB\x14\n\x12_targeted_center_yB\x0c\n\n_is_mentorB\x13\n\x11_software_versionB\x0e\n\x0c_module_nameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embodied.perception.vision.ImageToText_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGETOTEXTPB']._serialized_start=77
  _globals['_IMAGETOTEXTPB']._serialized_end=654
# @@protoc_insertion_point(module_scope)
