# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embodied/perception/vision/PeopleDetected.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'embodied/perception/vision/PeopleDetected.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/embodied/perception/vision/PeopleDetected.proto\x12\x1a\x65mbodied.perception.vision\"\xb8\x01\n\x08PersonPB\x12\x15\n\x08\x63\x65nter_x\x18\x01 \x01(\x02H\x00\x88\x01\x01\x12\x15\n\x08\x63\x65nter_y\x18\x02 \x01(\x02H\x01\x88\x01\x01\x12\x12\n\x05width\x18\x03 \x01(\x02H\x02\x88\x01\x01\x12\x13\n\x06height\x18\x04 \x01(\x02H\x03\x88\x01\x01\x12\x17\n\nconfidence\x18\x05 \x01(\x02H\x04\x88\x01\x01\x42\x0b\n\t_center_xB\x0b\n\t_center_yB\x08\n\x06_widthB\t\n\x07_heightB\r\n\x0b_confidence\"\xac\x02\n\x10PeopleDetectedPB\x12\x15\n\x08\x66rame_id\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12!\n\x14timestamp_deprecated\x18\x02 \x01(\x01H\x01\x88\x01\x01\x12\x34\n\x06people\x18\x03 \x03(\x0b\x32$.embodied.perception.vision.PersonPB\x12\x16\n\ttimestamp\x18\x04 \x01(\x04H\x02\x88\x01\x01\x12\x1d\n\x10software_version\x18\x64 \x01(\tH\x03\x88\x01\x01\x12\x18\n\x0bmodule_name\x18\x65 \x01(\tH\x04\x88\x01\x01\x42\x0b\n\t_frame_idB\x17\n\x15_timestamp_deprecatedB\x0c\n\n_timestampB\x13\n\x11_software_versionB\x0e\n\x0c_module_nameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embodied.perception.vision.PeopleDetected_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PERSONPB']._serialized_start=80
  _globals['_PERSONPB']._serialized_end=264
  _globals['_PEOPLEDETECTEDPB']._serialized_start=267
  _globals['_PEOPLEDETECTEDPB']._serialized_end=567
# @@protoc_insertion_point(module_scope)
