# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embodied/perception/vision/PosesEstimated.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'embodied/perception/vision/PosesEstimated.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/embodied/perception/vision/PosesEstimated.proto\x12\x1a\x65mbodied.perception.vision\"V\n\njointPosPB\x12\x12\n\x05index\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12\x0e\n\x01x\x18\x02 \x01(\x02H\x01\x88\x01\x01\x12\x0e\n\x01y\x18\x03 \x01(\x02H\x02\x88\x01\x01\x42\x08\n\x06_indexB\x04\n\x02_xB\x04\n\x02_y\"\xac\x01\n\x06PosePB\x12\x36\n\x06joints\x18\x01 \x03(\x0b\x32&.embodied.perception.vision.jointPosPB\x12\x15\n\x08\x63lass_id\x18\x02 \x01(\x04H\x00\x88\x01\x01\x12\x18\n\x0bnew_pose_id\x18\x03 \x01(\x04H\x01\x88\x01\x01\x12\x12\n\x05proba\x18\x04 \x01(\x02H\x02\x88\x01\x01\x42\x0b\n\t_class_idB\x0e\n\x0c_new_pose_idB\x08\n\x06_proba\"\xaa\x02\n\x10PosesEstimatedPB\x12\x15\n\x08\x66rame_id\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12!\n\x14timestamp_deprecated\x18\x02 \x01(\x01H\x01\x88\x01\x01\x12\x32\n\x06people\x18\x03 \x03(\x0b\x32\".embodied.perception.vision.PosePB\x12\x16\n\ttimestamp\x18\x04 \x01(\x04H\x02\x88\x01\x01\x12\x1d\n\x10software_version\x18\x64 \x01(\tH\x03\x88\x01\x01\x12\x18\n\x0bmodule_name\x18\x65 \x01(\tH\x04\x88\x01\x01\x42\x0b\n\t_frame_idB\x17\n\x15_timestamp_deprecatedB\x0c\n\n_timestampB\x13\n\x11_software_versionB\x0e\n\x0c_module_nameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embodied.perception.vision.PosesEstimated_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JOINTPOSPB']._serialized_start=79
  _globals['_JOINTPOSPB']._serialized_end=165
  _globals['_POSEPB']._serialized_start=168
  _globals['_POSEPB']._serialized_end=340
  _globals['_POSESESTIMATEDPB']._serialized_start=343
  _globals['_POSESESTIMATEDPB']._serialized_end=641
# @@protoc_insertion_point(module_scope)
