# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embodied/perception/vision/ShowState.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'embodied/perception/vision/ShowState.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*embodied/perception/vision/ShowState.proto\x12\x1a\x65mbodied.perception.vision\"\xa3\x03\n\tShowState\x12\x16\n\ttimestamp\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12=\n\x04type\x18\x02 \x01(\x0e\x32*.embodied.perception.vision.ShowState.TypeH\x01\x88\x01\x01\x12?\n\x05state\x18\x03 \x01(\x0e\x32+.embodied.perception.vision.ShowState.StateH\x02\x88\x01\x01\x12\x1d\n\x10software_version\x18\x64 \x01(\tH\x03\x88\x01\x01\x12\x18\n\x0bmodule_name\x18\x65 \x01(\tH\x04\x88\x01\x01\"F\n\x04Type\x12\x12\n\x0eTYPE_UNDEFINED\x10\x00\x12\x08\n\x04\x42OOK\x10\x01\x12\x0b\n\x07\x44RAWING\x10\x02\x12\t\n\x05\x41RUCO\x10\x03\x12\x08\n\x04\x46\x41\x43\x45\x10\x04\"7\n\x05State\x12\x13\n\x0fSTATE_UNDEFINED\x10\x00\x12\x0b\n\x07STARTED\x10\x01\x12\x0c\n\x08\x46INISHED\x10\x02\x42\x0c\n\n_timestampB\x07\n\x05_typeB\x08\n\x06_stateB\x13\n\x11_software_versionB\x0e\n\x0c_module_nameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embodied.perception.vision.ShowState_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SHOWSTATE']._serialized_start=75
  _globals['_SHOWSTATE']._serialized_end=494
  _globals['_SHOWSTATE_TYPE']._serialized_start=297
  _globals['_SHOWSTATE_TYPE']._serialized_end=367
  _globals['_SHOWSTATE_STATE']._serialized_start=369
  _globals['_SHOWSTATE_STATE']._serialized_end=424
# @@protoc_insertion_point(module_scope)
