# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embodied/robotbrain/serialized/CSData.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'embodied/robotbrain/serialized/CSData.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+embodied/robotbrain/serialized/CSData.proto\x12\x1e\x65mbodied.robotbrain.serialized\"\x92\x02\n\x06\x43SData\x12\x18\n\x0b\x63ontent_day\x18\x01 \x01(\rH\x00\x88\x01\x01\x12\x1c\n\x0f\x66orced_sleep_ts\x18\x02 \x01(\x04H\x01\x88\x01\x01\x12\x16\n\tmodule_id\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x17\n\ncontent_id\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\x1e\n\x11module_started_ts\x18\x05 \x01(\x04H\x04\x88\x01\x01\x12\x18\n\x0binstance_id\x18\x06 \x01(\rH\x05\x88\x01\x01\x42\x0e\n\x0c_content_dayB\x12\n\x10_forced_sleep_tsB\x0c\n\n_module_idB\r\n\x0b_content_idB\x14\n\x12_module_started_tsB\x0e\n\x0c_instance_idb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embodied.robotbrain.serialized.CSData_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CSDATA']._serialized_start=80
  _globals['_CSDATA']._serialized_end=354
# @@protoc_insertion_point(module_scope)
