# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embodied/robotbrain/serialized/FallbackInfo.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'embodied/robotbrain/serialized/FallbackInfo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from embodied.robotbrain import Contexts_pb2 as embodied_dot_robotbrain_dot_Contexts__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1embodied/robotbrain/serialized/FallbackInfo.proto\x12\x1e\x65mbodied.robotbrain.serialized\x1a\"embodied/robotbrain/Contexts.proto\"\xb2\x02\n\x0cNodeFallback\x12\x0f\n\x02id\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x32\n\x07\x63ontext\x18\x02 \x01(\x0b\x32\x1c.embodied.robotbrain.ContextH\x01\x88\x01\x01\x12N\n\x03opt\x18\x03 \x01(\x0e\x32<.embodied.robotbrain.serialized.NodeFallback.FallbackOptionsH\x02\x88\x01\x01\"r\n\x0f\x46\x61llbackOptions\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07\x44\x45\x46\x41ULT\x10\x01\x12\x10\n\x0c\x43ONVERSATION\x10\x02\x12\n\n\x06SILENT\x10\x03\x12\x0e\n\nLOCAL_ONLY\x10\x04\x12\x17\n\x13\x46\x41LLBACKS_NO_REMOTE\x10\x05\x42\x05\n\x03_idB\n\n\x08_contextB\x06\n\x04_opt\"k\n\x11\x43ontentIDFallback\x12\x0f\n\x02id\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x32\n\x07\x63ontext\x18\x02 \x01(\x0b\x32\x1c.embodied.robotbrain.ContextH\x01\x88\x01\x01\x42\x05\n\x03_idB\n\n\x08_context\"\xef\x02\n\x0eModuleFallback\x12\x0f\n\x02id\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x32\n\x07\x63ontext\x18\x02 \x01(\x0b\x32\x1c.embodied.robotbrain.ContextH\x01\x88\x01\x01\x12\x44\n\x0enode_fallbacks\x18\x03 \x03(\x0b\x32,.embodied.robotbrain.serialized.NodeFallback\x12O\n\x14\x63ontent_id_fallbacks\x18\x04 \x03(\x0b\x32\x31.embodied.robotbrain.serialized.ContentIDFallback\x12R\n\x17module_default_fallback\x18\x05 \x01(\x0b\x32,.embodied.robotbrain.serialized.NodeFallbackH\x02\x88\x01\x01\x42\x05\n\x03_idB\n\n\x08_contextB\x1a\n\x18_module_default_fallback\"\x9f\x01\n\x0c\x46\x61llbackInfo\x12:\n\x0f\x64\x65\x66\x61ult_context\x18\x01 \x01(\x0b\x32\x1c.embodied.robotbrain.ContextH\x00\x88\x01\x01\x12?\n\x07modules\x18\x02 \x03(\x0b\x32..embodied.robotbrain.serialized.ModuleFallbackB\x12\n\x10_default_contextb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embodied.robotbrain.serialized.FallbackInfo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NODEFALLBACK']._serialized_start=122
  _globals['_NODEFALLBACK']._serialized_end=428
  _globals['_NODEFALLBACK_FALLBACKOPTIONS']._serialized_start=287
  _globals['_NODEFALLBACK_FALLBACKOPTIONS']._serialized_end=401
  _globals['_CONTENTIDFALLBACK']._serialized_start=430
  _globals['_CONTENTIDFALLBACK']._serialized_end=537
  _globals['_MODULEFALLBACK']._serialized_start=540
  _globals['_MODULEFALLBACK']._serialized_end=907
  _globals['_FALLBACKINFO']._serialized_start=910
  _globals['_FALLBACKINFO']._serialized_end=1069
# @@protoc_insertion_point(module_scope)
