# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embodied/robotbrain/serialized/UserRecommendationData.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'embodied/robotbrain/serialized/UserRecommendationData.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;embodied/robotbrain/serialized/UserRecommendationData.proto\x12\x1e\x65mbodied.robotbrain.serialized\"\xbd\x05\n\x16UserRecommendationData\x12[\n\x0btag_history\x18\x01 \x03(\x0b\x32\x46.embodied.robotbrain.serialized.UserRecommendationData.TagHistoryEntry\x12\x64\n\x10random_tag_state\x18\x02 \x01(\x0b\x32\x45.embodied.robotbrain.serialized.UserRecommendationData.RandomTagStateH\x00\x88\x01\x01\x1a\x44\n\x0cSparseValues\x12\x12\n\x05value\x18\x01 \x01(\x02H\x00\x88\x01\x01\x12\x0f\n\x02id\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\x08\n\x06_valueB\x05\n\x03_id\x1a\x61\n\nTagHistory\x12S\n\x06values\x18\x01 \x03(\x0b\x32\x43.embodied.robotbrain.serialized.UserRecommendationData.SparseValues\x1a\x8c\x01\n\x0fTagHistoryEntry\x12\x10\n\x03key\x18\x01 \x01(\tH\x00\x88\x01\x01\x12U\n\x05value\x18\x02 \x01(\x0b\x32\x41.embodied.robotbrain.serialized.UserRecommendationData.TagHistoryH\x01\x88\x01\x01\x42\x06\n\x04_keyB\x08\n\x06_value\x1a\x92\x01\n\x0eRandomTagState\x12\x18\n\x0brandom_seed\x18\x01 \x01(\rH\x00\x88\x01\x01\x12\x19\n\x0cupdate_state\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x19\n\x0cweight_state\x18\x03 \x01(\tH\x02\x88\x01\x01\x42\x0e\n\x0c_random_seedB\x0f\n\r_update_stateB\x0f\n\r_weight_stateB\x13\n\x11_random_tag_stateb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embodied.robotbrain.serialized.UserRecommendationData_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERRECOMMENDATIONDATA']._serialized_start=96
  _globals['_USERRECOMMENDATIONDATA']._serialized_end=797
  _globals['_USERRECOMMENDATIONDATA_SPARSEVALUES']._serialized_start=317
  _globals['_USERRECOMMENDATIONDATA_SPARSEVALUES']._serialized_end=385
  _globals['_USERRECOMMENDATIONDATA_TAGHISTORY']._serialized_start=387
  _globals['_USERRECOMMENDATIONDATA_TAGHISTORY']._serialized_end=484
  _globals['_USERRECOMMENDATIONDATA_TAGHISTORYENTRY']._serialized_start=487
  _globals['_USERRECOMMENDATIONDATA_TAGHISTORYENTRY']._serialized_end=627
  _globals['_USERRECOMMENDATIONDATA_RANDOMTAGSTATE']._serialized_start=630
  _globals['_USERRECOMMENDATIONDATA_RANDOMTAGSTATE']._serialized_end=776
# @@protoc_insertion_point(module_scope)
