# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embodied/logging/Backup.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'embodied/logging/Backup.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x65mbodied/logging/Backup.proto\x12\x10\x65mbodied.logging\"\xe2\x01\n\x12\x42\x61\x63kupStageRequest\x12\x16\n\ttimestamp\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12\x11\n\x04path\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x1a\n\rend_timestamp\x18\x03 \x01(\x04H\x02\x88\x01\x01\x12\x1d\n\x10software_version\x18\x64 \x01(\tH\x03\x88\x01\x01\x12\x18\n\x0bmodule_name\x18\x65 \x01(\tH\x04\x88\x01\x01\x42\x0c\n\n_timestampB\x07\n\x05_pathB\x10\n\x0e_end_timestampB\x13\n\x11_software_versionB\x0e\n\x0c_module_name\"\xa1\x02\n\x10\x42\x61\x63kupDataUpdate\x12\x16\n\ttimestamp\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12\x12\n\x05\x61\x63tor\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x15\n\x08\x63omplete\x18\x03 \x01(\x08H\x02\x88\x01\x01\x12\x1d\n\x10\x65xtend_timestamp\x18\x04 \x01(\x04H\x03\x88\x01\x01\x12\x13\n\x0b\x66iles_added\x18\x05 \x03(\t\x12\x1d\n\x10software_version\x18\x64 \x01(\tH\x04\x88\x01\x01\x12\x18\n\x0bmodule_name\x18\x65 \x01(\tH\x05\x88\x01\x01\x42\x0c\n\n_timestampB\x08\n\x06_actorB\x0b\n\t_completeB\x13\n\x11_extend_timestampB\x13\n\x11_software_versionB\x0e\n\x0c_module_nameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embodied.logging.Backup_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BACKUPSTAGEREQUEST']._serialized_start=52
  _globals['_BACKUPSTAGEREQUEST']._serialized_end=278
  _globals['_BACKUPDATAUPDATE']._serialized_start=281
  _globals['_BACKUPDATAUPDATE']._serialized_end=570
# @@protoc_insertion_point(module_scope)
