# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embodied/logging/CloudStatus.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'embodied/logging/CloudStatus.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from embodied.logging import enums_pb2 as embodied_dot_logging_dot_enums__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"embodied/logging/CloudStatus.proto\x12\x10\x65mbodied.logging\x1a\x1c\x65mbodied/logging/enums.proto\"\x98\x01\n\x12\x43loudStatusRequest\x12\x16\n\ttimestamp\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12\x1d\n\x10software_version\x18\x64 \x01(\tH\x01\x88\x01\x01\x12\x18\n\x0bmodule_name\x18\x65 \x01(\tH\x02\x88\x01\x01\x42\x0c\n\n_timestampB\x13\n\x11_software_versionB\x0e\n\x0c_module_name\"\xbc\x03\n\x0b\x43loudStatus\x12\x16\n\ttimestamp\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12\x16\n\tconnected\x18\x02 \x01(\x08H\x01\x88\x01\x01\x12\x17\n\nuser_state\x18\x03 \x01(\rH\x02\x88\x01\x01\x12\x34\n\x08\x65ndpoint\x18\x04 \x01(\x0e\x32\x1d.embodied.logging.IOTEndpointH\x03\x88\x01\x01\x12\x1d\n\x10software_version\x18\x64 \x01(\tH\x04\x88\x01\x01\x12\x18\n\x0bmodule_name\x18\x65 \x01(\tH\x05\x88\x01\x01\"\x97\x01\n\tUserState\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x08\n\x04NONE\x10\x01\x12\x12\n\x0ePAIRED_PENDING\x10\x02\x12\x10\n\x0cPAIRED_VALID\x10\x03\x12\x14\n\x10UNPAIR_REQUESTED\x10\x04\x12\x0c\n\x08OTA_LOCK\x10\x05\x12\x13\n\x0fUNPAIR_WITH_RFS\x10\x06\x12\x14\n\x10USER_DATA_UPDATE\x10\x07\x42\x0c\n\n_timestampB\x0c\n\n_connectedB\r\n\x0b_user_stateB\x0b\n\t_endpointB\x13\n\x11_software_versionB\x0e\n\x0c_module_nameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embodied.logging.CloudStatus_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLOUDSTATUSREQUEST']._serialized_start=87
  _globals['_CLOUDSTATUSREQUEST']._serialized_end=239
  _globals['_CLOUDSTATUS']._serialized_start=242
  _globals['_CLOUDSTATUS']._serialized_end=686
  _globals['_CLOUDSTATUS_USERSTATE']._serialized_start=442
  _globals['_CLOUDSTATUS_USERSTATE']._serialized_end=593
# @@protoc_insertion_point(module_scope)
