# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embodied/logging/Family.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'embodied/logging/Family.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x65mbodied/logging/Family.proto\x12\x10\x65mbodied.logging\"\x94\x01\n\x11\x46\x61milyInformation\x12\x0f\n\x07members\x18\x01 \x03(\t\"n\n\x0b\x46\x61milyRoles\x12\x0c\n\x08guardian\x10\x00\x12\n\n\x06mother\x10\x01\x12\n\n\x06\x66\x61ther\x10\x02\x12\x0f\n\x0bgrandmother\x10\x03\x12\x0f\n\x0bgrandfather\x10\x04\x12\n\n\x06sister\x10\x05\x12\x0b\n\x07\x62rother\x10\x06\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embodied.logging.Family_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FAMILYINFORMATION']._serialized_start=52
  _globals['_FAMILYINFORMATION']._serialized_end=200
  _globals['_FAMILYINFORMATION_FAMILYROLES']._serialized_start=90
  _globals['_FAMILYINFORMATION_FAMILYROLES']._serialized_end=200
# @@protoc_insertion_point(module_scope)
