# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embodied/logging/LoggingState.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'embodied/logging/LoggingState.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from embodied.logging import enums_pb2 as embodied_dot_logging_dot_enums__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#embodied/logging/LoggingState.proto\x12\x10\x65mbodied.logging\x1a\x1c\x65mbodied/logging/enums.proto\"\xf9\x01\n\x19LoggingStateChangeRequest\x12\x32\n\x05state\x18\x01 \x01(\x0e\x32\x1e.embodied.logging.LoggingStateH\x00\x88\x01\x01\x12\x11\n\x04path\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x16\n\ttimestamp\x18\x03 \x01(\x04H\x02\x88\x01\x01\x12\x1d\n\x10software_version\x18\x64 \x01(\tH\x03\x88\x01\x01\x12\x18\n\x0bmodule_name\x18\x65 \x01(\tH\x04\x88\x01\x01\x42\x08\n\x06_stateB\x07\n\x05_pathB\x0c\n\n_timestampB\x13\n\x11_software_versionB\x0e\n\x0c_module_name\"\xaf\x03\n\x12LoggingStateUpdate\x12\x32\n\x05state\x18\x01 \x01(\x0e\x32\x1e.embodied.logging.LoggingStateH\x00\x88\x01\x01\x12\x11\n\x04path\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x11\n\x04uuid\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x16\n\ttimestamp\x18\x04 \x01(\x04H\x03\x88\x01\x01\x12\x16\n\tuser_uuid\x18\x05 \x01(\tH\x04\x88\x01\x01\x12\x19\n\x0csession_uuid\x18\x06 \x01(\tH\x05\x88\x01\x01\x12;\n\rupload_policy\x18\x07 \x01(\x0e\x32\x1f.embodied.logging.LoggingPolicyH\x06\x88\x01\x01\x12\x1d\n\x10software_version\x18\x64 \x01(\tH\x07\x88\x01\x01\x12\x18\n\x0bmodule_name\x18\x65 \x01(\tH\x08\x88\x01\x01\x42\x08\n\x06_stateB\x07\n\x05_pathB\x07\n\x05_uuidB\x0c\n\n_timestampB\x0c\n\n_user_uuidB\x0f\n\r_session_uuidB\x10\n\x0e_upload_policyB\x13\n\x11_software_versionB\x0e\n\x0c_module_nameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embodied.logging.LoggingState_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGGINGSTATECHANGEREQUEST']._serialized_start=88
  _globals['_LOGGINGSTATECHANGEREQUEST']._serialized_end=337
  _globals['_LOGGINGSTATEUPDATE']._serialized_start=340
  _globals['_LOGGINGSTATEUPDATE']._serialized_end=771
# @@protoc_insertion_point(module_scope)
