# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embodied/logging/SELUpdate.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'embodied/logging/SELUpdate.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n embodied/logging/SELUpdate.proto\x12\x10\x65mbodied.logging\"\x83\x02\n\tSELUpdate\x12\x16\n\tgoal_uuid\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x17\n\nlevel_uuid\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x16\n\ttimestamp\x18\x03 \x01(\x04H\x02\x88\x01\x01\x12\x16\n\tmodule_id\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\x1d\n\x10software_version\x18\x64 \x01(\tH\x04\x88\x01\x01\x12\x18\n\x0bmodule_name\x18\x65 \x01(\tH\x05\x88\x01\x01\x42\x0c\n\n_goal_uuidB\r\n\x0b_level_uuidB\x0c\n\n_timestampB\x0c\n\n_module_idB\x13\n\x11_software_versionB\x0e\n\x0c_module_name\"@\n\x0cSELUpdateSet\x12\x30\n\x0bsel_updates\x18\x01 \x03(\x0b\x32\x1b.embodied.logging.SELUpdateb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embodied.logging.SELUpdate_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SELUPDATE']._serialized_start=55
  _globals['_SELUPDATE']._serialized_end=314
  _globals['_SELUPDATESET']._serialized_start=316
  _globals['_SELUPDATESET']._serialized_end=380
# @@protoc_insertion_point(module_scope)
