# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embodied/logging/SomethingHappened.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'embodied/logging/SomethingHappened.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from embodied.logging import enums_pb2 as embodied_dot_logging_dot_enums__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(embodied/logging/SomethingHappened.proto\x12\x10\x65mbodied.logging\x1a\x1c\x65mbodied/logging/enums.proto\"\x98\x01\n\x12SomethingsNotRight\x12\x16\n\ttimestamp\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12\x1d\n\x10software_version\x18\x64 \x01(\tH\x01\x88\x01\x01\x12\x18\n\x0bmodule_name\x18\x65 \x01(\tH\x02\x88\x01\x01\x42\x0c\n\n_timestampB\x13\n\x11_software_versionB\x0e\n\x0c_module_nameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embodied.logging.SomethingHappened_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SOMETHINGSNOTRIGHT']._serialized_start=93
  _globals['_SOMETHINGSNOTRIGHT']._serialized_end=245
# @@protoc_insertion_point(module_scope)
