# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embodied/logging/SystemMetrics.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'embodied/logging/SystemMetrics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$embodied/logging/SystemMetrics.proto\x12\x10\x65mbodied.logging\"\x89\x03\n\x0bSystemState\x12\x16\n\ttimestamp\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12\x14\n\x07\x43PULoad\x18\x02 \x01(\x02H\x01\x88\x01\x01\x12\x14\n\x07RAMFree\x18\x03 \x01(\rH\x02\x88\x01\x01\x12\x15\n\x08\x44iskFree\x18\x04 \x01(\x02H\x03\x88\x01\x01\x12\x13\n\x06Uptime\x18\x05 \x01(\x04H\x04\x88\x01\x01\x12\x18\n\x0bTemperature\x18\x06 \x01(\rH\x05\x88\x01\x01\x12\x14\n\x07\x42\x61ttery\x18\x07 \x01(\rH\x06\x88\x01\x01\x12\x15\n\x08WifiRssi\x18\x08 \x01(\x05H\x07\x88\x01\x01\x12\x1d\n\x10software_version\x18\x64 \x01(\tH\x08\x88\x01\x01\x12\x18\n\x0bmodule_name\x18\x65 \x01(\tH\t\x88\x01\x01\x42\x0c\n\n_timestampB\n\n\x08_CPULoadB\n\n\x08_RAMFreeB\x0b\n\t_DiskFreeB\t\n\x07_UptimeB\x0e\n\x0c_TemperatureB\n\n\x08_BatteryB\x0b\n\t_WifiRssiB\x13\n\x11_software_versionB\x0e\n\x0c_module_nameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embodied.logging.SystemMetrics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SYSTEMSTATE']._serialized_start=59
  _globals['_SYSTEMSTATE']._serialized_end=452
# @@protoc_insertion_point(module_scope)
