syntax = "proto3";
// file: embodied/perception/vision/FacesTracked.proto  package: embodied.perception.vision
package embodied.perception.vision;
message WorldPosition {
  optional float center_x = 1;
  optional float center_y = 2;
  optional float center_z = 3;
  optional float width = 4;
  optional float height = 5;
}
message TrackedFacePB {
  optional float center_x = 1;
  optional float center_y = 2;
  optional float width = 3;
  optional float height = 4;
  optional float confidence = 5;
  optional string name = 6;
  optional uint64 id = 7;
  optional float pitch = 8;
  optional float yaw = 9;
  optional float roll = 10;
  optional uint64 emotion = 11;
  optional float emotion_proba = 12;
  optional float left_eye_x = 13;
  optional float left_eye_y = 14;
  optional float right_eye_x = 15;
  optional float right_eye_y = 16;
  optional embodied.perception.vision.WorldPosition world_position = 17;
  optional float name_confidence = 18;
  optional float occlusion = 19;
  optional string gesture = 20;
  repeated uint64 id_history = 21;
  optional int64 last_detected = 22;
  optional float initial_confidence = 23;
}
message FacesTrackedPB {
  optional uint64 frame_id = 1;
  optional double timestamp_deprecated = 2;
  repeated embodied.perception.vision.TrackedFacePB tracked_people = 3;
  optional uint64 timestamp = 4;
  optional string software_version = 100;
  optional string module_name = 101;
}
