#!/usr/bin/env python3
"""
Check that every internal markdown link in the repo resolves — BOTH the target file
AND the #anchor fragment. Run from repo root:
    python3 scripts/check-doc-links.py
Exit 1 if any relative link points at a missing file, or at a #section that no heading
in the target doc produces. Skips external (http/mailto) links.

Anchor validation mirrors the docs explorer's resolver (sim/web/docs.html `anchorEl` →
`slugify`): an anchor is valid iff it equals slugify(heading textContent) for some
heading in the target doc. Keeping this in sync is what makes the explorer's
cross-document deep links actually scroll. Used to keep docs/reverse-engineering/*,
tools/*/README.md, etc. navigable.
"""
import os, re, glob, sys

def slugify(text):
    """Replicate sim/web/docs.html `slugify` exactly (JS \\w == [A-Za-z0-9_], ASCII)."""
    t = text.strip().lower()
    t = re.sub(r'[^a-z0-9_\- ]+', '', t)   # drop anything but word chars / hyphen / space
    t = re.sub(r'\s+', '-', t)
    t = re.sub(r'-+', '-', t)
    return t

def heading_text(raw):
    """The rendered textContent of a heading (strip inline markdown marked would drop)."""
    t = raw
    t = re.sub(r'`([^`]*)`', r'\1', t)                 # inline code
    t = re.sub(r'!\[([^\]]*)\]\([^)]*\)', r'\1', t)    # images -> alt
    t = re.sub(r'\[([^\]]*)\]\([^)]*\)', r'\1', t)     # links  -> text
    t = re.sub(r'\*\*([^*]+)\*\*', r'\1', t)           # bold
    t = re.sub(r'\*([^*]+)\*', r'\1', t)               # italic
    t = re.sub(r'__([^_]+)__', r'\1', t)
    return t

_anchor_cache = {}
def anchors_of(md):
    """The set of anchor slugs the headings in file `md` produce (cached)."""
    if md in _anchor_cache:
        return _anchor_cache[md]
    slugs, in_fence = set(), False
    try:
        lines = open(md, encoding="utf-8", errors="ignore").read().splitlines()
    except OSError:
        _anchor_cache[md] = slugs; return slugs
    for line in lines:
        if line.lstrip().startswith("```"):
            in_fence = not in_fence; continue
        if in_fence:
            continue
        m = re.match(r'^(#{1,6})\s+(.*?)\s*#*\s*$', line)
        if m:
            slugs.add(slugify(heading_text(m.group(2))))
    _anchor_cache[md] = slugs
    return slugs

def main():
    broken_file, broken_anchor, checked, files = [], [], 0, 0
    for md in glob.glob("**/*.md", recursive=True):
        if "/.git/" in md:
            continue
        # sim/web/docs-bundle/ is a GENERATED byte-for-byte copy of docs/ for the static
        # docs explorer; its links are correct at the originals' location (already checked).
        if md.replace(os.sep, "/").startswith("sim/web/docs-bundle/"):
            continue
        if "/node_modules/" in md:
            continue
        files += 1
        base = os.path.dirname(md)
        txt = open(md, encoding="utf-8", errors="ignore").read()
        for m in re.finditer(r'\[[^\]]*\]\(([^)]+)\)', txt):
            link = m.group(1).strip()
            if re.match(r'^(https?:|mailto:)', link):
                continue
            path, _, anchor = link.partition('#')
            # resolve the target file (same file for a bare #anchor link)
            if not path:
                target = md
            else:
                checked += 1
                target = os.path.normpath(os.path.join(base, path))
                if not os.path.exists(target):
                    broken_file.append((md, link, target)); continue
            # validate the #anchor against the target doc's headings (only for .md targets).
            # Compare the RAW anchor (as the explorer's anchorEl does: it matches the URL
            # fragment against slugify(heading text) / the heading id, without re-slugifying
            # the fragment) — so a malformed anchor like `foo--bar` or `Foo` is caught, not
            # silently normalized.
            if anchor and target.lower().endswith(".md"):
                checked += 1
                if anchor not in anchors_of(target):
                    broken_anchor.append((md, link, target))

    print(f"checked {checked} internal links across {files} markdown files")
    rc = 0
    if broken_file:
        print(f"\n{len(broken_file)} BROKEN FILE LINKS:")
        for md, link, tgt in broken_file:
            print(f"  {md}: [{link}] -> {tgt}")
        rc = 1
    if broken_anchor:
        print(f"\n{len(broken_anchor)} BROKEN ANCHORS (target file exists, but no heading matches #section):")
        for md, link, tgt in broken_anchor:
            print(f"  {md}: [{link}]")
        rc = 1
    if not rc:
        print("all internal links + anchors resolve ✅")
    return rc

if __name__ == "__main__":
    sys.exit(main())
