syntax = "proto3";
// file: embodied/robotbrain/ContentMetaTags.proto  package: embodied.robotbrain
package embodied.robotbrain;
import "embodied/robotbrain/ContentTags.proto";
message CognitiveTag {
  optional string name = 1;
  optional string uuid = 2;
  optional uint64 value = 3;
}
message IntimacyTag {
  optional string name = 1;
  optional string uuid = 2;
  optional uint64 order = 3;
}
message ContentMetaList {
  repeated embodied.robotbrain.CognitiveTag cognitive_load = 1;
  repeated embodied.robotbrain.IntimacyTag intimacy_level = 2;
  repeated embodied.robotbrain.Tag topics = 3;
  repeated embodied.robotbrain.Tag genres = 4;
}
